package com.integrosys.cms.app.excludedfacility.bus;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.techinfra.ejbsupport.ConcurrentUpdateException;

public interface IExcludedFacilityBusManager {

	SearchResult getAllExcludedFacility()throws ExcludedFacilityException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	SearchResult getSearchedExcludedFacility(String type,String text)throws ExcludedFacilityException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IExcludedFacility createExcludedFacility(IExcludedFacility excludedFacility)throws ExcludedFacilityException;
	IExcludedFacility getExcludedFacilityById(long id) throws ExcludedFacilityException,TrxParameterException,TransactionException;
	IExcludedFacility updateExcludedFacility(IExcludedFacility item) throws ExcludedFacilityException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IExcludedFacility updateToWorkingCopy(IExcludedFacility workingCopy, IExcludedFacility imageCopy) throws ExcludedFacilityException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	public boolean isExcludedFacilityDescriptionUnique(String excludedFacilityDescription);
}
