package com.integrosys.cms.app.valuationAmountAndRating.proxy;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.uiinfra.exception.CommandProcessingException;
import com.integrosys.cms.app.valuationAmountAndRating.bus.IValuationAmountAndRating;
import com.integrosys.cms.app.valuationAmountAndRating.bus.OBValuationAmountAndRating;
import com.integrosys.cms.app.valuationAmountAndRating.bus.ValuationAmountAndRatingException;
import com.integrosys.cms.app.valuationAmountAndRating.trx.IValuationAmountAndRatingTrxValue;
import com.integrosys.cms.app.transaction.ITrxContext;
import com.integrosys.cms.app.transaction.OBTrxContext;

public interface IValuationAmountAndRatingProxyManager {

	public SearchResult getAllActualValuationAmountAndRating() throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public IValuationAmountAndRatingTrxValue makerCreateValuationAmountAndRating(ITrxContext anITrxContext, IValuationAmountAndRating anICCValuationAmountAndRating)throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public IValuationAmountAndRatingTrxValue getValuationAmountAndRatingByTrxID(String aTrxID) throws ValuationAmountAndRatingException,TransactionException,CommandProcessingException;
	
	public IValuationAmountAndRatingTrxValue checkerApproveValuationAmountAndRating(ITrxContext anITrxContext, IValuationAmountAndRatingTrxValue anIValuationAmountAndRatingTrxValue) throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public boolean isProductCodeUnique(String productCode);
	
	public IValuationAmountAndRatingTrxValue makerUpdateSaveUpdateValuationAmountAndRating(ITrxContext anITrxContext, IValuationAmountAndRatingTrxValue anICCValuationAmountAndRatingTrxValue, IValuationAmountAndRating anICCValuationAmountAndRating)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public IValuationAmountAndRatingTrxValue makerSaveValuationAmountAndRating(ITrxContext anITrxContext, IValuationAmountAndRating anICCValuationAmountAndRating)throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	//added by santosh
	public IValuationAmountAndRatingTrxValue getValuationAmountAndRatingTrxValue(long productCode)
			throws ValuationAmountAndRatingException,TransactionException,CommandProcessingException;

	public IValuationAmountAndRatingTrxValue makerUpdateValuationAmountAndRating(OBTrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn,
			OBValuationAmountAndRating valuationAmountAndRating)throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public IValuationAmountAndRatingTrxValue checkerRejectValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;

	public IValuationAmountAndRatingTrxValue makerEditRejectedValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn,IValuationAmountAndRating anICCValuationAmountAndRating)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;

	public IValuationAmountAndRatingTrxValue makerCloseRejectedValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;

	public IValuationAmountAndRatingTrxValue makerUpdateSaveCreateValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn,IValuationAmountAndRating anICCValuationAmountAndRating)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public IValuationAmountAndRatingTrxValue makerCloseDraftValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	
	public SearchResult getAllFilteredActualValuationAmountAndRating(String code,String name)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;

	public IValuationAmountAndRatingTrxValue makerDeleteValuationAmountAndRating(ITrxContext ctx, IValuationAmountAndRatingTrxValue trxValueIn,IValuationAmountAndRating anICCValuationAmountAndRating)
			throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
}
