package com.integrosys.cms.app.email.notification.bus;

import com.integrosys.base.techinfra.propertyfile.PropertyManager;


public interface INotificationQuery {
	
	public String STATEMENT_CODE_FORM8			=	PropertyManager.getValue("notification.NOT0013.form8.statement.code","FORM8");
	public String STATEMENT_TYPE_CALL_MEMO		=	PropertyManager.getValue("notification.NOT0014.callmemo.statement.type","CALL_MEMO");
	public String STATEMENT_TYPE_PLANT_VISIT	=	PropertyManager.getValue("notification.NOT0015.plantvisit.statement.type","PLANT_VISIT");
	
	
	public String CAM_EXPIRY_SQL = new StringBuffer("SELECT ")
								.append(" subprofile.cms_le_sub_profile_id as partyID,")
								.append(" subprofile.lsp_short_name as partyName,")
								.append("  to_char(cam.LLP_NEXT_ANNL_RVW_DATE,'DD-Mon-YYYY') as camExpiryDate ")
								.append(" FROM SCI_LSP_LMT_PROFILE cam, ")
								.append(" SCI_LE_SUB_PROFILE subProfile ")
								.append(" WHERE TRUNC(cam.LLP_NEXT_ANNL_RVW_DATE) = TRUNC(sysdate)")
								.append(" AND subprofile.status                   ='ACTIVE'")
								.append(" AND subprofile.cms_le_sub_profile_id=cam.cms_customer_id")
								.toString();

	public String CAM_NOT_CREATED_SQL = new StringBuffer("SELECT ")
								.append(" subprofile.cms_le_sub_profile_id as partyID,")
								.append("  subprofile.lsp_short_name             AS partyName ")
								.append(" FROM SCI_LE_SUB_PROFILE subProfile, ")
								.append(" TRANSACTION trx ")
								.append(" WHERE subprofile.status                   ='ACTIVE' ")
								.append(" AND subprofile.CMS_LE_SUB_PROFILE_ID NOT IN(SELECT CAM.CMS_CUSTOMER_ID FROM SCI_LSP_LMT_PROFILE CAM) ")
								.append(" AND trx.transaction_type = 'CUSTOMER' ")
								.append(" AND TRX.REFERENCE_ID =  subprofile.CMS_LE_SUB_PROFILE_ID ")
								.append(" and (trunc(sysdate)-trunc(trx.creation_date))=16 ")
								.append(" ORDER BY partyName")
								.toString();

	public String LAD_DUE_SQL = new StringBuffer(" SELECT ")
								.append(" subprofile.cms_le_sub_profile_id as partyID,")
								.append(" subprofile.lsp_short_name as partyName,")
								.append(" to_char(lad.lad_due_date,'DD-Mon-YYYY') as ladDueDate")
								.append(" FROM sci_lsp_lmt_profile cam,")
								.append("   sci_le_sub_profile subProfile,")
								.append("  cms_lad lad")
								.append(" WHERE subprofile.status                   ='ACTIVE'")
								.append(" AND subprofile.cms_le_sub_profile_id=cam.cms_customer_id")
								.append(" AND lad.limit_profile_id=cam.cms_lsp_lmt_profile_id ") 
								.append(" and lad.generation_date=(select max(inlad.generation_date) from cms_lad inLad where inlad.limit_profile_id=cam.cms_lsp_lmt_profile_id)")
								.append(" AND (trunc(lad.lad_due_date) - trunc(sysdate))  in (90,60,30,0)")
								
								//.append(" AND trunc(lad.lad_due_date)=trunc(sysdate)")
								.toString();

	public String LAD_EXPIRY_SQL = new StringBuffer(" SELECT Distinct ")
								.append(" subprofile.cms_le_sub_profile_id AS partyID, ")
								.append(" subprofile.lsp_short_name as partyName, ")
								.append(" to_char((SELECT trunc(expiry_date)  FROM CMS_CHECKLIST_ITEM  WHERE DOC_ITEM_ID = GET_DOC_ITEM_ID(lmt.CMS_LIMIT_PROFILE_ID)),'DD-Mon-YYYY') as ladExpiryDate ")
								.append(" FROM  sci_le_sub_profile subProfile, ")
								.append("   SCI_LSP_LMT_PROFILE pf,  SCI_LSP_APPR_LMTS lmt ")
								.append(" WHERE subprofile.status                   ='ACTIVE'")
								.append(" AND subProfile.cms_le_sub_profile_id = pf.cms_customer_id ")
								.append(" AND pf.cms_lsp_lmt_profile_id           = lmt.CMS_LIMIT_PROFILE_ID ") 
								.append(" AND trunc(sysdate) = (SELECT trunc(expiry_date)  FROM ")
								.append(" CMS_CHECKLIST_ITEM  WHERE DOC_ITEM_ID = GET_DOC_ITEM_ID(lmt.CMS_LIMIT_PROFILE_ID)) ")
								.toString();

	public String IMAGE_NOT_TAGGED_SQL = new StringBuffer("  SELECT " )
								.append(" sub_profile.cms_le_sub_profile_id as partyID,")
								.append(" sub_profile.lsp_short_name as partyName,")
								.append("   to_char(trx.creation_date,'DD-Mon-YYYY') as camCreationDate")
								.append("  FROM SCI_LE_SUB_PROFILE sub_profile ,")
								.append("    sci_lsp_lmt_profile lmt_profile ,")
								.append("    cms_checklist_item checklistItem ,")
								.append("    cms_checklist checklist,")
								.append("    transaction trx")
								.append("  WHERE sub_profile.lsp_le_id         =lmt_profile.llp_le_id")
								.append("  AND sub_profile.status='ACTIVE'")
								.append("  AND checklist.cms_lsp_lmt_profile_id=lmt_profile.CMS_LSP_LMT_PROFILE_ID")
								.append("  AND checklistitem.checklist_id      =checklist.checklist_id")
								.append("  AND checklistitem.doc_item_id NOT  IN")
								.append("    (SELECT doc_desc")
								.append("    FROM cms_image_tag_details")
								.append("    WHERE cust_id=sub_profile.lsp_le_id")
								.append("    )")
								.append("  AND lmt_profile.cms_lsp_lmt_profile_id =trx.reference_id")
								.append("  AND trx.transaction_type='LIMITPROFILE'")
								.append("  And trunc(trx.creation_date)=trunc(sysdate-7)")
								.append("  group by sub_profile.lsp_short_name, sub_profile.cms_le_sub_profile_id, trx.creation_date")
								.append("  ORDER BY partyName")
								.toString();

	public String GET_PARTY_WITH_STALE_CHEQUE_SQL = new StringBuffer(" SELECT ")
													.append(" sp.cms_le_sub_profile_id as partyID,")
													.append(" sp.lsp_short_name as partyName,")
													.append("   cam.cms_lsp_lmt_profile_id,")
													.append("   lsm.cms_collateral_id")
													.append(" FROM SCI_LE_SUB_PROFILE sp,")
													.append("   sci_lsp_lmt_profile cam,")
													.append("   cms_limit_security_map lsm,")
													.append("   sci_lsp_appr_lmts lmts,")
													.append("   CMS_ASSET_PDC pdc")
													.append(" WHERE sp.status                          ='ACTIVE'")
													.append(" AND sp.cms_le_sub_profile_id             =cam.cms_customer_id")
													.append(" AND cam.cms_lsp_lmt_profile_id           = lmts.CMS_LIMIT_PROFILE_ID")
													.append(" AND lmts.cms_lsp_appr_lmts_id            = lsm.cms_lsp_appr_lmts_id")
													.append(" AND (lsm.update_status_ind              <> 'D'")
													.append(" OR lsm.update_status_ind                IS NULL)")
													.append(" AND pdc.cms_collateral_id                =lsm.cms_collateral_id")
													.append(" AND(TRUNC(sysdate)-TRUNC(pdc.issue_date))=183")
													.append(" GROUP BY lsm.cms_collateral_id,")
													.append(" sp.cms_le_sub_profile_id,")
													.append("   sp.lsp_short_name,")
													.append("   cam.cms_lsp_lmt_profile_id")
													.toString();

	public String GET_PARTY_WITH_MATURE_SECURITY_SQL = new StringBuffer	(" SELECT partyID, partyName,")
													.append("   secType,")
													.append("   secSubType,")
													.append("   maturityDate,")
													.append("   cmv")
													.append(" FROM")
													.append("   (SELECT party.cms_le_sub_profile_id AS partyID,")
													.append("     party.lsp_short_name              AS partyName,")
													.append("     cam.llp_bca_ref_num               AS camNo,")
													.append("     lmt.cms_lsp_appr_lmts_id          AS facilityID,")
													.append("     sec.cms_collateral_id             AS collateralId,")
													.append("     '1'                               AS part,")
													.append("     0                                 AS unqid,")
													.append("     sec.security_sub_type_id          AS subTypeId,")
													.append("     sec.type_name                     AS secType,")
													.append("     sec.subtype_name                  AS secSubType,")
													.append("     to_char(sec.security_maturity_date,'DD-Mon-YYYY')        AS maturityDate,")
													.append("     COALESCE(sec.cmv,0)                           AS CMV")
													.append("   FROM cms_security sec,")
													.append("     cms_limit_security_map lsm,")
													.append("     sci_le_sub_profile party,")
													.append("     sci_lsp_lmt_profile cam,")
													.append("     SCI_LSP_APPR_LMTS lmt")
													.append("   WHERE sec.cms_collateral_id           = lsm.cms_collateral_id")
													.append("   AND party.status                      ='ACTIVE'")
													.append("   AND cam.cms_customer_id               =party.cms_le_sub_profile_id")
													.append("   AND cam.cms_lsp_lmt_profile_id        =lmt.cms_limit_profile_id")
													.append("   AND lsm.cms_lsp_appr_lmts_id          =lmt.cms_lsp_appr_lmts_id")
													.append("   AND sec.security_sub_type_id NOT     IN ('AB108','MS610','MS600','CS202')")
													.append("   AND TRUNC(sec.security_maturity_date) =TRUNC(sysdate)")
													.append("   UNION")
													.append("   SELECT party.cms_le_sub_profile_id AS partyID,")
													.append("     party.lsp_short_name             AS partyName,")
													.append("     cam.llp_bca_ref_num              AS camNo,")
													.append("     lmt.cms_lsp_appr_lmts_id         AS facilityID,")
													.append("     sec.cms_collateral_id            AS collateralId,")
													.append("     '2'                              AS part,")
													.append("     bond.feed_id                     AS unqid,")
													.append("     sec.security_sub_type_id         AS subTypeId,")
													.append("     sec.type_name                    AS secType,")
													.append("     sec.subtype_name                 AS secSubType,")
													.append("     to_char(bond.maturity_date,'DD-Mon-YYYY')               AS maturityDate,")
													.append("     COALESCE(sec.cmv,0)    AS CMV")
													.append("   FROM cms_security sec,")
													.append("     cms_limit_security_map lsm,")
													.append("     cms_portfolio_item portfolio,")
													.append("     cms_price_feed bond,")
													.append("     sci_le_sub_profile party,")
													.append("     sci_lsp_lmt_profile cam,")
													.append("     SCI_LSP_APPR_LMTS lmt")
													.append("   WHERE sec.cms_collateral_id   = lsm.cms_collateral_id")
													.append("   AND party.status              ='ACTIVE'")
													.append("   AND cam.cms_customer_id       =party.cms_le_sub_profile_id")
													.append("   AND cam.cms_lsp_lmt_profile_id=lmt.cms_limit_profile_id")
													.append("   AND lsm.cms_lsp_appr_lmts_id  =lmt.cms_lsp_appr_lmts_id")
													.append("   AND sec.security_sub_type_id  ='MS610'")
													.append("   AND sec.cms_collateral_id     =portfolio.cms_collateral_id")
													.append("   AND portfolio.stock_code      =bond.bond_code")
													.append("   AND TRUNC(bond.maturity_date) =TRUNC(sysdate)")
													.append("   UNION")
													.append("   SELECT party.cms_le_sub_profile_id AS partyID,")
													.append("     party.lsp_short_name             AS partyName,")
													.append("     cam.llp_bca_ref_num              AS camNo,")
													.append("     lmt.cms_lsp_appr_lmts_id         AS facilityID,")
													.append("     sec.cms_collateral_id            AS collateralId,")
													.append("     '3'                              AS part,")
													.append("     mfund.feed_id                    AS unqid ,")
													.append("     sec.security_sub_type_id         AS subTypeId,")
													.append("     sec.type_name                    AS secType,")
													.append("     sec.subtype_name                 AS secSubType,")
													.append("     to_char(mfund.expiry_date,'DD-Mon-YYYY')                AS maturityDate,")
													.append("     COALESCE(sec.cmv,0)                   AS CMV")
													.append("   FROM cms_security sec,")
													.append("     cms_limit_security_map lsm,")
													.append("     cms_portfolio_item portfolio,")
													.append("     CMS_MUTUAL_FUNDS_FEED mfund,")
													.append("     sci_le_sub_profile party,")
													.append("     sci_lsp_lmt_profile cam,")
													.append("     SCI_LSP_APPR_LMTS lmt")
													.append("   WHERE sec.cms_collateral_id   = lsm.cms_collateral_id")
													.append("   AND party.status              ='ACTIVE'")
													.append("   AND cam.cms_customer_id       =party.cms_le_sub_profile_id")
													.append("   AND cam.cms_lsp_lmt_profile_id=lmt.cms_limit_profile_id")
													.append("   AND lsm.cms_lsp_appr_lmts_id  =lmt.cms_lsp_appr_lmts_id")
													.append("   AND sec.security_sub_type_id  ='MS600'")
													.append("   AND sec.cms_collateral_id     =portfolio.cms_collateral_id")
													.append("   AND mfund.scheme_type         ='CLOSE'")
													.append("   AND portfolio.stock_code      =mfund.scheme_code")
													.append("   AND TRUNC(mfund.expiry_date)  =TRUNC(sysdate)")
													.append("   )")
													.append(" GROUP BY partyID, partyName,")
													.append("   secType,")
													.append("   secSubType,")
													.append("   maturityDate,")
													.append("   cmv")
													.append(" ORDER BY partyName")
											.toString();

	public String GET_PARTY_WITH_MATURE_SECURITY_INSURANCE_SQL = new StringBuffer(" SELECT ")
																.append(" sp.cms_le_sub_profile_id                 AS partyID," )
																.append(" sp.LSP_SHORT_NAME                AS partyName,")
																.append("   cs.subtype_name                       AS secSubType,")
																.append("   TO_CHAR(ip.EXPIRY_DATE,'DD-Mon-YYYY') AS insuranceMaturityDate")
																.append(" FROM SCI_LE_SUB_PROFILE sp,")
																.append("   SCI_LSP_LMT_PROFILE cam,")
																.append("   SCI_LSP_APPR_LMTS lmts,")
																.append("   CMS_LIMIT_SECURITY_MAP lsm,")
																.append("   CMS_SECURITY cs,")
																.append("   CMS_INSURANCE_POLICY ip")
																.append(" WHERE sp.CMS_LE_SUB_PROFILE_ID = cam.CMS_CUSTOMER_ID")
																.append(" AND cam.CMS_LSP_LMT_PROFILE_ID = lmts.CMS_LIMIT_PROFILE_ID")
																.append(" AND lmts.CMS_LSP_APPR_LMTS_ID  = lsm.CMS_LSP_APPR_LMTS_ID")
																.append(" AND (lsm.UPDATE_STATUS_IND    != 'D'")
																.append(" OR lsm.UPDATE_STATUS_IND      IS NULL)")
																.append(" AND cs.CMS_COLLATERAL_ID       = lsm.CMS_COLLATERAL_ID")
																.append(" AND cs.CMS_COLLATERAL_ID       = ip.CMS_COLLATERAL_ID")
																.append(" AND TRUNC(ip.EXPIRY_DATE)      = TRUNC(SYSDATE)")
																.append(" UNION ")
																.append(" SELECT ")
																.append(" sp.cms_le_sub_profile_id                 AS partyID," )
																.append(" sp.LSP_SHORT_NAME                AS partyName,")
																.append("   cs.subtype_name                       AS secSubType,")
																.append("   TO_CHAR(gcdet.insurance_expiry_date,'DD-Mon-YYYY') AS insuranceMaturityDate")
																.append(" FROM SCI_LE_SUB_PROFILE sp,")
																.append("   SCI_LSP_LMT_PROFILE cam,")
																.append("   SCI_LSP_APPR_LMTS lmts,")
																.append("   CMS_LIMIT_SECURITY_MAP lsm,")
																.append("   CMS_SECURITY cs,")
																.append("   CMS_ASSET_GC_DET gc,")
																.append("   CMS_ASSET_GC_STOCK_DET gcdet")
																.append(" WHERE sp.CMS_LE_SUB_PROFILE_ID = cam.CMS_CUSTOMER_ID")
																.append(" AND sp.status = 'ACTIVE' ")
																.append(" AND cam.CMS_LSP_LMT_PROFILE_ID = lmts.CMS_LIMIT_PROFILE_ID")
																.append(" AND lmts.CMS_LSP_APPR_LMTS_ID  = lsm.CMS_LSP_APPR_LMTS_ID")
																.append(" AND (lsm.UPDATE_STATUS_IND    != 'D' OR lsm.UPDATE_STATUS_IND      IS NULL)")
																.append(" AND cs.CMS_COLLATERAL_ID       = lsm.CMS_COLLATERAL_ID")
																.append(" and cs.security_sub_type_id ='AB100'")
																.append(" and cs.cms_collateral_id=gc.cms_collateral_id")
																.append(" and gc.gc_det_id=gcdet.gc_det_id ")
																.append(" and gc.due_date=( SELECT MAX(DUE_DATE) FROM CMS_ASSET_GC_DET WHERE CMS_COLLATERAL_ID = cs.CMS_COLLATERAL_ID )")
																.append(" and gcdet.stock_type ='CurrentAsset'")
																.append(" and gcdet.has_insurance='Y'")
																.append(" AND TRUNC(gcdet.insurance_expiry_date)      = TRUNC(SYSDATE)")
															.toString();
	
	public String GET_PARTIES_HAVING_DOCUMENT_DUE_SQL = new StringBuffer(" SELECT sp.cms_le_sub_profile_id                    AS partyID,")
														.append("   sp.lsp_short_name                                AS partyName,")
														.append("   recmaster.statement_type                         AS statementType,")
														.append("   chkitem.status                                   AS status,")
														.append("   TO_CHAR(chkItem.expiry_date,'DD-Mon-YYYY')       AS docExpiryDate,")
														.append("   TO_CHAR(chkitem.defer_expiry_date,'DD-Mon-YYYY') AS docDeferDate")
														.append(" FROM sci_lsp_lmt_profile pf,")
														.append("   sci_le_sub_profile sp,")
														.append("   CMS_CHECKLIST chk,")
														.append("   CMS_CHECKLIST_ITEM chkItem,")
														.append("   CMS_DOCUMENT_GLOBALLIST recMaster")
														.append(" WHERE sp.cms_le_sub_profile_id                           = pf.cms_customer_id")
														.append(" AND chk.cms_lsp_lmt_profile_id                           =pf.cms_lsp_lmt_profile_id")
														.append(" AND chk.category                                         ='REC'")
														.append(" AND chk.checklist_id                                     = chkitem.checklist_id")
														.append(" AND chkitem.document_code                                =recmaster.document_code")
														.append(" AND recmaster.statement_type IN ('"+STATEMENT_TYPE_CALL_MEMO+"','"+STATEMENT_TYPE_PLANT_VISIT+"')")
														.append(" AND ((chkitem.status                                     ='AWAITING'")
														.append(" AND chkitem.expiry_date                                 IS NOT NULL")
														.append(" AND (TRUNC(chkitem.expiry_date) - TRUNC(sysdate))       <=7 )")
														.append(" OR (chkitem.status                                       ='DEFERRED'")
														.append(" AND chkitem.defer_expiry_date                           IS NOT NULL")
														.append(" AND (TRUNC(chkitem.defer_expiry_date) - TRUNC(sysdate)) <=7))")
														.append(" GROUP BY sp.cms_le_sub_profile_id,")
														.append("   sp.lsp_short_name,")
														.append("   recmaster.statement_type,")
														.append("   chkItem.expiry_date,")
														.append("   chkitem.defer_expiry_date,")
														.append("   chkitem.status")
														.append(" UNION")
														.append(" SELECT sp.cms_le_sub_profile_id                    AS partyID,")
														.append("   sp.lsp_short_name                                AS partyName,")
														.append("   'FORM8'                                          AS statementType,")
														.append("   chkitem.status                                   AS status,")
														.append("   TO_CHAR(chkItem.expiry_date,'DD-Mon-YYYY')       AS docExpiryDate,")
														.append("   TO_CHAR(chkitem.defer_expiry_date,'DD-Mon-YYYY') AS docDeferDate")
														.append(" FROM sci_lsp_lmt_profile pf,")
														.append("   sci_le_sub_profile sp,")
														.append("   CMS_CHECKLIST chk,")
														.append("   CMS_CHECKLIST_ITEM chkItem,")
														.append("   CMS_DOCUMENT_GLOBALLIST recMaster")
														.append(" WHERE sp.cms_le_sub_profile_id                           = pf.cms_customer_id")
														.append(" AND chk.cms_lsp_lmt_profile_id                           =pf.cms_lsp_lmt_profile_id")
														.append(" AND chk.category                                         ='O'")
														.append(" AND chk.checklist_id                                     = chkitem.checklist_id")
														.append(" AND chkitem.document_code                                =recmaster.document_code")
														.append(" AND chkitem.document_code                                ='"+STATEMENT_CODE_FORM8+"'")
														.append(" AND ((chkitem.status                                     ='AWAITING'")
														.append(" AND chkitem.expiry_date                                 IS NOT NULL")
														.append(" AND (TRUNC(chkitem.expiry_date) - TRUNC(sysdate))       <=7 )")
														.append(" OR (chkitem.status                                       ='DEFERRED'")
														.append(" AND chkitem.defer_expiry_date                           IS NOT NULL")
														.append(" AND (TRUNC(chkitem.defer_expiry_date) - TRUNC(sysdate)) <=7))")
														.append(" GROUP BY sp.cms_le_sub_profile_id,")
														.append("   sp.lsp_short_name,")
														.append("   recmaster.statement_type,")
														.append("   chkItem.expiry_date,")
														.append("   chkitem.defer_expiry_date,")
														.append("   chkitem.status")
														.toString();	
	

	public String GET_CASECREATION_DISTINCT_BRANCH_SQL = new StringBuffer	("select DISTINCT cc.branchcode as branch ")
														
														.append("  from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														//.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='1') ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, subp.lsp_sgmnt_code_value ")
														.append(" order by cc.branchcode ").toString();
	
	public String GET_CASECREATION_DISTINCT_SEGMENT_SQL = new StringBuffer	("select DISTINCT commonC.entry_name  as segment ")
	
														.append("  from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ").toString();
														
	
	public String GET_CASECREATION_CPUT_REQUESTED_SQL = new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,(select count(*) from cms_casecreation_item ccitem where ")
														.append(" ccitem.casecreationid=cc.id  and ccitem.status='1' and trunc(ccitem.requested_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" ) as doc_nos from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='1') ")
														.append(" and trunc(cc.creation_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks")
														.append(" order by cc.branchcode ").toString();
	
	
	public String GET_CASECREATION_BRANCH_SENT_SQL = new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,(select count(*) from cms_casecreation_item ccitem where ")
														.append(" ccitem.casecreationid=cc.id and ccitem.status='2' and trunc(ccitem.dispatched_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" ) as doc_nos from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='2' and trunc(cms_casecreation_item.dispatched_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ) ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks")
														.append(" order by cc.branchcode ").toString();
	
	
	public String GET_CASECREATION_CPUT_RECEIVED_SQL = new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,(select count(*) from cms_casecreation_item ccitem where ")
														.append(" ccitem.casecreationid=cc.id and ccitem.status='3' and trunc(RECEIVED_DATE)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" ) as doc_nos from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ") 
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='3' and trunc(RECEIVED_DATE)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE')  ) ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks ")
														.append(" order by cc.branchcode  ").toString();
	
	public String GET_CASECREATION_CPUT_WRONG_REQUEST_SQL = new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,(select count(*) from cms_casecreation_item ccitem where ")
														.append(" ccitem.casecreationid=cc.id and ccitem.status='4' and trunc(ccitem.wrong_req_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" ) as doc_nos from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='4' and trunc(cms_casecreation_item.wrong_req_date)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ) ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks")
														.append(" order by cc.branchcode ").toString();

	/*public String GET_CASECREATION_CPUT_NOT_REC_SQL = new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,(select count(*) from cms_casecreation_item ccitem where ")
														.append(" ccitem.casecreationid=cc.id and ccitem.status='2' and cal_expiry_date(dispatched_date,3,1)<=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(" ) as doc_nos from cms_casecreationupdate cc , ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")
														.append(" where ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")
														.append(" and lp.llp_le_id= subp.lsp_le_id ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='2' and cal_expiry_date(dispatched_date,3,1)<=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE'))   ")
														.append(" group by cc.id, cc.creation_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks")
														.append(" order by cc.branchcode ").toString();*/

	
	public String GET_CASECREATION_CPUT_NOT_REC_SQL =  new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks,")
														.append("(select count(*) from cms_casecreation_item ccitem where  ")
														.append("ccitem.casecreationid=cc.id  and ccitem.status='2' and cal_expiry_date(dispatched_date,3,1)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE') ")
														.append(") as doc_nos , ")
														.append("calendar_days((select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE'),cc.last_update_date) as pendingDays")
														.append(" from cms_casecreationupdate cc ,  ")
														.append(" sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC")  
														.append(" where  ")
														.append(" cc.limit_profile_id= lp.cms_lsp_lmt_profile_id")  
														.append(" and lp.llp_le_id= subp.lsp_le_id  ")
														.append(" and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE")  
														.append(" and cc.id in (select casecreationid from cms_casecreation_item where status  ='2' and cal_expiry_date(dispatched_date,3,1)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) from  cms_general_param gp where gp.param_code='APPLICATION_DATE'))")  
														.append(" group by cc.id, cc.creation_date,cc.last_update_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks ")
														.append(" order by cc.branchcode ").toString() ;
	
	
	
	public String GET_CASECREATION_BRANCH_NOT_SENT_SQL =  new StringBuffer	("select cc.id as caseCreationId,TO_CHAR(cc.creation_date,'DD-Mon-YYYY') as creation_date,subp.ulsp_short_name as partyName,subp.lsp_le_id as partyId, commonC.entry_name as Segment ,cc.branchcode as branch,cc.curr_remarks as remarks, ")
														.append("(select count(*) from cms_casecreation_item ccitem where  ")
														.append("ccitem.casecreationid=cc.id  and ccitem.status='1' ")
														.append("and cal_expiry_date(REQUESTED_DATE,3,1)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) ") 
														.append("from  cms_general_param gp where gp.param_code='APPLICATION_DATE') and dispatched_date is null ")
														.append(") as doc_nos ")
														.append(",calendar_days((select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) ") 
														.append("from  cms_general_param gp where gp.param_code='APPLICATION_DATE'),cc.creation_date) as pendingDays ")
														.append("from cms_casecreationupdate cc ,  ")
														.append("sci_lsp_lmt_profile lp,sci_le_sub_profile subp , common_code_category_entry commonC ")  
														.append("where  ")
														.append("cc.limit_profile_id= lp.cms_lsp_lmt_profile_id ")  
														.append("and lp.llp_le_id= subp.lsp_le_id  ")
														.append("and commonC.entry_code=subp.LSP_SGMNT_CODE_VALUE ")  
														.append("and cc.id in (select casecreationid from cms_casecreation_item where status  ='1' ") 
														.append("and cal_expiry_date(REQUESTED_DATE,3,1)=(select trunc(TO_TIMESTAMP(gp.param_value,'DD/MM/YYYY')) ") 
														.append("from  cms_general_param gp where gp.param_code='APPLICATION_DATE') and dispatched_date is null ) ")  
														.append("group by cc.id, cc.creation_date,cc.last_update_date,cc.branchcode, subp.ulsp_short_name, subp.lsp_le_id, commonC.entry_name ,cc.curr_remarks ") 
														.append("order by cc.branchcode ").toString() ;


	
	
}
