package com.integrosys.cms.app.collateral.bus.type.property;

import java.io.Serializable;
import java.util.Date;

	public interface IPropertyValuation3 extends Serializable {
		
		public long getId();
		public void setId(long id);
		public long getCollateralId();
		public void setCollateralId(long collateralId);
		public String getSubTypeName();
		public void setSubTypeName(String subTypeName);
		public String getTypeName();
		public void setTypeName(String typeName);
		public String getSciRefNote();
		public void setSciRefNote(String sciRefNote);
		public String getSecurityCurrency();
		public void setSecurityCurrency(String securityCurrency);
		public String getSecPriority();
		public void setSecPriority(String secPriority);
		public String getMonitorProcess();
		public void setMonitorProcess(String monitorProcess);
		public String getMonitorFrequency();
		public void setMonitorFrequency(String monitorFrequency);
		public String getSecLocation();
		public void setSecLocation(String secLocation);
		public String getSecOrganization();
		public void setSecOrganization(String secOrganization);
		public String getCollateralCode();
		public void setCollateralCode(String collateralCode);
		public String getRevalFrequency();
		public void setRevalFrequency(String revalFrequency);
		public Date getNextValuationDate();
		public void setNextValuationDate(Date nextValuationDate);
		public String getChangeType();
		public void setChangeType(String changeType);
		public String getOtherBankCharge();
		public void setOtherBankCharge(String otherBankCharge);
		public String getSecOwnership();
		public void setSecOwnership(String secOwnership);
		public String getOwnerOfProperty();
		public void setOwnerOfProperty(String ownerOfProperty);
		public String getThirdPartyEntity();
		public void setThirdPartyEntity(String thirdPartyEntity);
		public String getCinThirdParty();
		public void setCinThirdParty(String cinThirdParty);
		public String getCersaiTrxRefNo();
		public void setCersaiTrxRefNo(String cersaiTrxRefNo);
		public String getCersaiSecurityInterestId();
		public void setCersaiSecurityInterestId(String cersaiSecurityInterestId);
		public String getCersaiAssetId();
		public void setCersaiAssetId(String cersaiAssetId);
		public Date getDateCersaiRegi();
		public void setDateCersaiRegi(Date dateCersaiRegi);
		public Date getCersaiRegDate();
		public void setCersaiRegDate(Date cersaiRegDate);
		public String getCersaiId();
		public void setCersaiId(String cersaiId);
		public Date getSaleDeedPurchaseDate();
		public void setSaleDeedPurchaseDate(Date saleDeedPurchaseDate);
		public String getThirdPartyAddress();
		public void setThirdPartyAddress(String thirdPartyAddress);
		public String getThirdPartyState();
		public void setThirdPartyState(String thirdPartyState);
		public String getThirdPartyCity();
		public void setThirdPartyCity(String thirdPartyCity);
		public String getThirdPartyPincode();
		public void setThirdPartyPincode(String thirdPartyPincode);
		public String getPropertyId();
		public void setPropertyId(String propertyId);
		public String getDescOfAsset();
		public void setDescOfAsset(String descOfAsset);
		public String getPropertyType();
		public void setPropertyType(String propertyType);
		public String getSalePurchaseValue();
		public void setSalePurchaseValue(String salePurchaseValue);
		public Date getSalePurchaseDate();
		public void setSalePurchaseDate(Date salePurchaseDate);
		public String getMortgageType();
		public void setMortgageType(String mortgageType);
		public String getMortgagecretaedBy();
		public void setMortgagecretaedBy(String mortgagecretaedBy);
		public String getDocumentReceived();
		public void setDocumentReceived(String documentReceived);
		public String getDocumentBlock();
		public void setDocumentBlock(String documentBlock);
		public String getBinNumber();
		public void setBinNumber(String binNumber);
		public String getClaim();
		public void setClaim(String claim);
		public String getClaimType();
		public void setClaimType(String claimType);
		public String getAdvocateLawyerName();
		public void setAdvocateLawyerName(String advocateLawyerName);
		public String getDeveloperGroupCompany();
		public void setDeveloperGroupCompany(String developerGroupCompany);
		public String getLotNo();
		public void setLotNo(String lotNo);
		public String getLotNumberPrefix();
		public void setLotNumberPrefix(String lotNumberPrefix);
		public String getPropertyLotLocation();
		public void setPropertyLotLocation(String propertyLotLocation);
		public String getOtherCity();
		public void setOtherCity(String otherCity);
		public String getPropertyAddress();
		public void setPropertyAddress(String propertyAddress);
		public String getPropertyAddress2();
		public void setPropertyAddress2(String propertyAddress2);
		public String getPropertyAddress3();
		public void setPropertyAddress3(String propertyAddress3);
		public String getPropertyAddress4();
		public void setPropertyAddress4(String propertyAddress4);
		public String getPropertyAddress5();
		public void setPropertyAddress5(String propertyAddress5);
		public String getPropertyAddress6();
		public void setPropertyAddress6(String propertyAddress6);
		public String getProjectName();
		public void setProjectName(String projectName);
		public Date getValuationDateV3();
		public void setValuationDateV3(Date valuationDateV3);
		public String getValuatorCompanyV3();
		public void setValuatorCompanyV3(String valuatorCompanyV3);
		public String getTotalPropertyAmontV3();
		public void setTotalPropertyAmontV3(String totalPropertyAmontV3);
		public String getCategoryOfLandUseV3();
		public void setCategoryOfLandUseV3(String categoryOfLandUseV3);
		public String getDeveloperNameV3();
		public void setDeveloperNameV3(String developerNameV3);
		public String getCountryV3();
		public void setCountryV3(String countryV3);
		public String getRegionV3();
		public void setRegionV3(String regionV3) ;
		public String getStateV3();
		public void setStateV3(String stateV3);
		public String getNearestCityV3();
		public void setNearestCityV3(String nearestCityV3);
		public String getPincodeV3();
		public void setPincodeV3(String pincodeV3);
		public double getLandAreaV3();
		public void setLandAreaV3(double landAreaV3);
		public String getLandAreaUOMV3();
		public void setLandAreaUOMV3(String landAreaUOMV3);
		public double getInSqfLandAreaV3();
		public void setInSqfLandAreaV3(double inSqfLandAreaV3);
		public double getBuildupAreaV3();
		public void setBuildupAreaV3(double buildupAreaV3);
		public String getBuildupAreaUOMV3();
		public void setBuildupAreaUOMV3(String buildupAreaUOMV3);
		public double getInSqfbuildupAreaV3();
		public void setInSqfbuildupAreaV3(double inSqfbuildupAreaV3);
		public char getPropertyCompletionStatusV3();
		public void setPropertyCompletionStatusV3(char propertyCompletionStatusV3);
		public double getLandValueIRBV3();
		public void setLandValueIRBV3(double landValueIRBV3);
		public double getBuildingValueIRBV3();
		public void setBuildingValueIRBV3(double buildingValueIRBV3);
		public double getReconstructionValueIRBV3();
		public void setReconstructionValueIRBV3(double reconstructionValueIRBV3);
		public Boolean getIsPhyInspectionV3();
		public void setIsPhyInspectionV3(Boolean isPhyInspectionV3);
		public String getPhyInspectionFreqUnitV3();
		public void setPhyInspectionFreqUnitV3(String phyInspectionFreqUnitV3);
		public Date getLastPhyInspectionDateV3();
		public void setLastPhyInspectionDateV3(Date lastPhyInspectionDateV3);
		public Date getNextPhyInspectionDateV3();
		public void setNextPhyInspectionDateV3(Date nextPhyInspectionDateV3);
		public String getRemarksPropertyV3();
		public void setRemarksPropertyV3(String remarksPropertyV3);
		public String getEnvironmentRiskyStatus();
		public void setEnvironmentRiskyStatus(String environmentRiskyStatus);
		public Date getEnvironmentRiskDate();
		public void setEnvironmentRiskDate(Date environmentRiskDate);
		public Date getTsrDate();
		public void setTsrDate(Date tsrDate);
		public Date getNextTsrDate();
		public void setNextTsrDate(Date nextTsrDate);
		public String getTsrFrequency();
		public void setTsrFrequency(String tsrFrequency);
		public String getConstitution();
		public void setConstitution(String constitution);
		public String getEnvironmentRiskRemark();
		public void setEnvironmentRiskRemark(String environmentRiskRemark);
		public Date getLegalAuditDate();
		public void setLegalAuditDate(Date legalAuditDate);
		public Date getInterveingPeriSerachDate();
		public void setInterveingPeriSerachDate(Date interveingPeriSerachDate);
		public Date getDateOfReceiptTitleDeed();
		public void setDateOfReceiptTitleDeed(Date dateOfReceiptTitleDeed);
		public Date getValCreationDateV3();
		public void setValCreationDateV3(Date valCreationDateV3);
		
		/*public String getMortgageCreationAdd();
		public void setMortgageCreationAdd(String mortgageCreationAdd);*/
		public Date getPreviousMortCreationDate();
		public void setPreviousMortCreationDate(Date previousMortCreationDate);
		
		public String getPropertyUsage();
		public void setPropertyUsage(String propertyUsage);
		public String getMortageRegisteredRef();
		public void setMortageRegisteredRef(String mortageRegisteredRef);

		
}
