package com.integrosys.cms.app.collateral.bus.type.property;

import java.io.Serializable;
import java.util.Date;

	public interface IPropertyValuation1 extends Serializable {
		
		public long getId();
		public void setId(long id);
		public long getCollateralId();
		public void setCollateralId(long collateralId);
		public String getSubTypeName();
		public void setSubTypeName(String subTypeName);
		public String getTypeName();
		public void setTypeName(String typeName);
		public String getSciRefNote();
		public void setSciRefNote(String sciRefNote);
		public String getSecurityCurrency();
		public void setSecurityCurrency(String securityCurrency);
		public String getSecPriority();
		public void setSecPriority(String secPriority);
		public String getMonitorProcess();
		public void setMonitorProcess(String monitorProcess);
		public String getMonitorFrequency();
		public void setMonitorFrequency(String monitorFrequency);
		public String getSecLocation();
		public void setSecLocation(String secLocation);
		public String getSecOrganization();
		public void setSecOrganization(String secOrganization);
		public String getCollateralCode();
		public void setCollateralCode(String collateralCode);
		public String getRevalFrequency();
		public void setRevalFrequency(String revalFrequency);
		public Date getNextValuationDate();
		public void setNextValuationDate(Date nextValuationDate);
		public String getChangeType();
		public void setChangeType(String changeType);
		public String getOtherBankCharge();
		public void setOtherBankCharge(String otherBankCharge);
		public String getSecOwnership();
		public void setSecOwnership(String secOwnership);
		public String getOwnerOfProperty();
		public void setOwnerOfProperty(String ownerOfProperty);
		public String getThirdPartyEntity();
		public void setThirdPartyEntity(String thirdPartyEntity);
		public String getCinThirdParty();
		public void setCinThirdParty(String cinThirdParty);
		public String getCersaiTrxRefNo();
		public void setCersaiTrxRefNo(String cersaiTrxRefNo);
		public String getCersaiSecurityInterestId();
		public void setCersaiSecurityInterestId(String cersaiSecurityInterestId);
		public String getCersaiAssetId();
		public void setCersaiAssetId(String cersaiAssetId);
		public Date getDateCersaiRegi();
		public void setDateCersaiRegi(Date dateCersaiRegi);
		public Date getCersaiRegDate();
		public void setCersaiRegDate(Date cersaiRegDate);
		public String getCersaiId();
		public void setCersaiId(String cersaiId);
		public Date getSaleDeedPurchaseDate();
		public void setSaleDeedPurchaseDate(Date saleDeedPurchaseDate);
		public String getThirdPartyAddress();
		public void setThirdPartyAddress(String thirdPartyAddress);
		public String getThirdPartyState();
		public void setThirdPartyState(String thirdPartyState);
		public String getThirdPartyCity();
		public void setThirdPartyCity(String thirdPartyCity);
		public String getThirdPartyPincode();
		public void setThirdPartyPincode(String thirdPartyPincode);
		public String getPropertyId();
		public void setPropertyId(String propertyId);
		public String getDescOfAsset();
		public void setDescOfAsset(String descOfAsset);
		public String getPropertyType();
		public void setPropertyType(String propertyType);
		public String getSalePurchaseValue();
		public void setSalePurchaseValue(String salePurchaseValue);
		public Date getSalePurchaseDate();
		public void setSalePurchaseDate(Date salePurchaseDate);
		public String getMortgageType();
		public void setMortgageType(String mortgageType);
		public String getMortgagecretaedBy();
		public void setMortgagecretaedBy(String mortgagecretaedBy);
		public String getDocumentReceived();
		public void setDocumentReceived(String documentReceived);
		public String getDocumentBlock();
		public void setDocumentBlock(String documentBlock);
		public String getBinNumber();
		public void setBinNumber(String binNumber);
		public String getClaim();
		public void setClaim(String claim);
		public String getClaimType();
		public void setClaimType(String claimType);
		public String getAdvocateLawyerName();
		public void setAdvocateLawyerName(String advocateLawyerName);
		public String getDeveloperGroupCompany();
		public void setDeveloperGroupCompany(String developerGroupCompany);
		public String getLotNo();
		public void setLotNo(String lotNo);
		public String getLotNumberPrefix();
		public void setLotNumberPrefix(String lotNumberPrefix);
		public String getPropertyLotLocation();
		public void setPropertyLotLocation(String propertyLotLocation);
		public String getOtherCity();
		public void setOtherCity(String otherCity);
		public String getPropertyAddress();
		public void setPropertyAddress(String propertyAddress);
		public String getPropertyAddress2();
		public void setPropertyAddress2(String propertyAddress2);
		public String getPropertyAddress3();
		public void setPropertyAddress3(String propertyAddress3);
		public String getPropertyAddress4();
		public void setPropertyAddress4(String propertyAddress4);
		public String getPropertyAddress5();
		public void setPropertyAddress5(String propertyAddress5);
		public String getPropertyAddress6();
		public void setPropertyAddress6(String propertyAddress6);
		public String getProjectName();
		public void setProjectName(String projectName);
		public Date getValuationDateV1();
		public void setValuationDateV1(Date valuationDateV1);
		public String getValuatorCompanyV1();
		public void setValuatorCompanyV1(String valuatorCompanyV1);
		public String getTotalPropertyAmontV1();
		public void setTotalPropertyAmontV1(String totalPropertyAmontV1);
		public String getCategoryOfLandUseV1();
		public void setCategoryOfLandUseV1(String categoryOfLandUseV1);
		public String getDeveloperNameV1();
		public void setDeveloperNameV1(String developerNameV1);
		public String getCountryV1();
		public void setCountryV1(String countryV1);
		public String getRegionV1();
		public void setRegionV1(String regionV1) ;
		public String getStateV1();
		public void setStateV1(String stateV1);
		public String getNearestCityV1();
		public void setNearestCityV1(String nearestCityV1);
		public String getPincodeV1();
		public void setPincodeV1(String pincodeV1);
		public double getLandAreaV1();
		public void setLandAreaV1(double landAreaV1);
		public String getLandAreaUOMV1();
		public void setLandAreaUOMV1(String landAreaUOMV1);
		public double getInSqfLandAreaV1();
		public void setInSqfLandAreaV1(double inSqfLandAreaV1);
		public double getBuildupAreaV1();
		public void setBuildupAreaV1(double buildupAreaV1);
		public String getBuildupAreaUOMV1();
		public void setBuildupAreaUOMV1(String buildupAreaUOMV1);
		public double getInSqfbuildupAreaV1();
		public void setInSqfbuildupAreaV1(double inSqfbuildupAreaV1);
		public char getPropertyCompletionStatusV1();
		public void setPropertyCompletionStatusV1(char propertyCompletionStatusV1);
		public double getLandValueIRBV1();
		public void setLandValueIRBV1(double landValueIRBV1);
		public double getBuildingValueIRBV1();
		public void setBuildingValueIRBV1(double buildingValueIRBV1);
		public double getReconstructionValueIRBV1();
		public void setReconstructionValueIRBV1(double reconstructionValueIRBV1);
		public Boolean getIsPhyInspectionV1();
		public void setIsPhyInspectionV1(Boolean isPhyInspectionV1);
		public String getPhyInspectionFreqUnitV1();
		public void setPhyInspectionFreqUnitV1(String phyInspectionFreqUnitV1);
		public Date getLastPhyInspectionDateV1();
		public void setLastPhyInspectionDateV1(Date lastPhyInspectionDateV1);
		public Date getNextPhyInspectionDateV1();
		public void setNextPhyInspectionDateV1(Date nextPhyInspectionDateV1);
		public String getRemarksPropertyV1();
		public void setRemarksPropertyV1(String remarksPropertyV1);
		public String getEnvironmentRiskyStatus();
		public void setEnvironmentRiskyStatus(String environmentRiskyStatus);
		public Date getEnvironmentRiskDate();
		public void setEnvironmentRiskDate(Date environmentRiskDate);
		public Date getTsrDate();
		public void setTsrDate(Date tsrDate);
		public Date getNextTsrDate();
		public void setNextTsrDate(Date nextTsrDate);
		public String getTsrFrequency();
		public void setTsrFrequency(String tsrFrequency);
		public String getConstitution();
		public void setConstitution(String constitution);
		public String getEnvironmentRiskRemark();
		public void setEnvironmentRiskRemark(String environmentRiskRemark);
		public Date getLegalAuditDate();
		public void setLegalAuditDate(Date legalAuditDate);
		public Date getInterveingPeriSerachDate();
		public void setInterveingPeriSerachDate(Date interveingPeriSerachDate);
		public Date getDateOfReceiptTitleDeed();
		public void setDateOfReceiptTitleDeed(Date dateOfReceiptTitleDeed);
		public Date getValCreationDateV1();
		public void setValCreationDateV1(Date valCreationDateV1);
		
		/*public String getMortgageCreationAdd();
		public void setMortgageCreationAdd(String mortgageCreationAdd);*/
		public Date getPreviousMortCreationDate();
		public void setPreviousMortCreationDate(Date previousMortCreationDate);

		public String getPropertyUsage();
		public void setPropertyUsage(String propertyUsage);
		public String getMortageRegisteredRef();
		public void setMortageRegisteredRef(String mortageRegisteredRef);
		
}
