package com.integrosys.cms.app.insurancecoveragedtls.proxy;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.techinfra.ejbsupport.ConcurrentUpdateException;
import com.integrosys.base.uiinfra.exception.CommandProcessingException;
import com.integrosys.cms.app.insurancecoverage.bus.InsuranceCoverageException;
import com.integrosys.cms.app.insurancecoverage.trx.IInsuranceCoverageTrxValue;
import com.integrosys.cms.app.insurancecoveragedtls.bus.InsuranceCoverageDtlsException;
import com.integrosys.cms.app.insurancecoveragedtls.trx.IInsuranceCoverageDtlsTrxValue;
import com.integrosys.cms.app.transaction.ITrxContext;
import com.integrosys.cms.ui.insurancecoverage.IInsuranceCoverage;
import com.integrosys.cms.ui.insurancecoveragedtls.IInsuranceCoverageDtls;

/**
 * Insurance Coverage Details Proxy Manager
 * 
 * @author Dattatray Thorat
 * @version $Revision: 1.0 $
 */

public interface IInsuranceCoverageDtlsProxyManager {
	
	public SearchResult getInsuranceCoverageDtlsList();
	
	public boolean isICCodeUnique(String rmCode);
	
	public IInsuranceCoverageDtlsTrxValue makerCreateInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anIInsuranceCoverageDtlsTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverageDtls)
		throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtls getInsuranceCoverageDtlsById(long id) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtls createInsuranceCoverageDtls(IInsuranceCoverageDtls InsuranceCoverageDtls) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	 
	public IInsuranceCoverageDtls updateInsuranceCoverageDtls(IInsuranceCoverageDtls InsuranceCoverageDtls) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	
	public IInsuranceCoverageDtls deleteInsuranceCoverageDtls(IInsuranceCoverageDtls InsuranceCoverageDtls) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerUpdateInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anICCInsuranceCoverageDtlsTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverageDtls)
		throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerEditRejectedInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anIInsuranceCoverageDtlsTrxValue, IInsuranceCoverageDtls anInsuranceCoverageDtls) 
		throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue getInsuranceCoverageDtlsTrxValue(long aInsuranceCoverageDtlsId) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;

	public IInsuranceCoverageDtlsTrxValue makerDeleteInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anICCInsuranceCoverageDtlsTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverageDtls)
		throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue getInsuranceCoverageDtlsByTrxID(String aTrxID) throws InsuranceCoverageDtlsException,TransactionException,CommandProcessingException;
	
	public IInsuranceCoverageDtlsTrxValue checkerApproveInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anIInsuranceCoverageDtlsTrxValue) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue checkerRejectInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anIInsuranceCoverageDtlsTrxValue) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;

	public IInsuranceCoverageDtlsTrxValue makerCloseRejectedInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anISystemBankTrxValue) throws InsuranceCoverageDtlsException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerCloseDraftInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anISystemBankTrxValue) throws InsuranceCoverageException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerUpdateCreateInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anICCInsuranceCoverageTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverage)
		throws InsuranceCoverageException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerUpdateSaveInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anICCInsuranceCoverageTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverage)
		throws InsuranceCoverageException,TrxParameterException,TransactionException;
	
	public IInsuranceCoverageDtlsTrxValue makerSaveInsuranceCoverageDtls(ITrxContext anITrxContext, IInsuranceCoverageDtlsTrxValue anIInsuranceCoverageDtlsTrxValue, IInsuranceCoverageDtls anICCInsuranceCoverage)
		throws InsuranceCoverageException,TrxParameterException,TransactionException;
}
