package com.integrosys.cms.app.limit.bus;

import java.io.Serializable;

public interface ILimitProfileUdf extends Serializable {

	public String getUdf1();
	public String getUdf2();
	public String getUdf3();
	public String getUdf4();
	public String getUdf5();
	public String getUdf6();
	public String getUdf7();
	public String getUdf8();
	public String getUdf9();
	public String getUdf10();
	public String getUdf11();
	public String getUdf12();
	public String getUdf13();
	public String getUdf14();
	public String getUdf15();
	public String getUdf16();
	public String getUdf17();
	public String getUdf18();
	public String getUdf19();
	public String getUdf20();
	public String getUdf21();
	public String getUdf22();
	public String getUdf23();
	public String getUdf24();
	public String getUdf25();
	public String getUdf26();
	public String getUdf27();
	public String getUdf28();
	public String getUdf29();
	public String getUdf30();
	public String getUdf31();
	public String getUdf32();
	public String getUdf33();
	public String getUdf34();
	public String getUdf35();
	public String getUdf36();
	public String getUdf37();
	public String getUdf38();
	public String getUdf39();
	public String getUdf40();
	public String getUdf41();
	public String getUdf42();
	public String getUdf43();
	public String getUdf44();
	public String getUdf45();
	public String getUdf46();
	public String getUdf47();
	public String getUdf48();
	public String getUdf49();
	public String getUdf50();
	public void setUdf1(String udf);
	public void setUdf2(String udf);
	public void setUdf3(String udf);
	public void setUdf4(String udf);
	public void setUdf5(String udf);
	public void setUdf6(String udf);
	public void setUdf7(String udf);
	public void setUdf8(String udf);
	public void setUdf9(String udf);
	public void setUdf10(String udf);
	public void setUdf11(String udf);
	public void setUdf12(String udf);
	public void setUdf13(String udf);
	public void setUdf14(String udf);
	public void setUdf15(String udf);
	public void setUdf16(String udf);
	public void setUdf17(String udf);
	public void setUdf18(String udf);
	public void setUdf19(String udf);
	public void setUdf20(String udf);
	public void setUdf21(String udf);
	public void setUdf22(String udf);
	public void setUdf23(String udf);
	public void setUdf24(String udf);
	public void setUdf25(String udf);
	public void setUdf26(String udf);
	public void setUdf27(String udf);
	public void setUdf28(String udf);
	public void setUdf29(String udf);
	public void setUdf30(String udf);
	public void setUdf31(String udf);
	public void setUdf32(String udf);
	public void setUdf33(String udf);
	public void setUdf34(String udf);
	public void setUdf35(String udf);
	public void setUdf36(String udf);
	public void setUdf37(String udf);
	public void setUdf38(String udf);
	public void setUdf39(String udf);
	public void setUdf40(String udf);
	public void setUdf41(String udf);
	public void setUdf42(String udf);
	public void setUdf43(String udf);
	public void setUdf44(String udf);
	public void setUdf45(String udf);
	public void setUdf46(String udf);
	public void setUdf47(String udf);
	public void setUdf48(String udf);
	public void setUdf49(String udf);
	public void setUdf50(String udf);
    public  String getUdf51();
    public  String getUdf52();
    public  String getUdf53();
    public  String getUdf54();
    public  String getUdf55();
    public  String getUdf56();
    public  String getUdf57();
    public  String getUdf58();
    public  String getUdf59();
    public  String getUdf60();
    public  String getUdf61();
    public  String getUdf62();
    public  String getUdf63();
    public  String getUdf64();
    public  String getUdf65();
    public  String getUdf66();
    public  String getUdf67();
    public  String getUdf68();
    public  String getUdf69();
    public  String getUdf70();
    public  String getUdf71();
    public  String getUdf72();
    public  String getUdf73();
    public  String getUdf74();
    public  String getUdf75();
    public  String getUdf76();
    public  String getUdf77();
    public  String getUdf78();
    public  String getUdf79();
    public  String getUdf80();
    public  String getUdf81();
    public  String getUdf82();
    public  String getUdf83();
    public  String getUdf84();
    public  String getUdf85();
    public  String getUdf86();
    public  String getUdf87();
    public  String getUdf88();
    public  String getUdf89();
    public  String getUdf90();
    public  String getUdf91();
    public  String getUdf92();
    public  String getUdf93();
    public  String getUdf94();
    public  String getUdf95();
    public  String getUdf96();
    public  String getUdf97();
    public  String getUdf98();
    public  String getUdf99();
    public  String getUdf100();
    public  void setUdf51(String udf51);
    public  void setUdf52(String udf52);
    public  void setUdf53(String udf53);
    public  void setUdf54(String udf54);
    public  void setUdf55(String udf55);
    public  void setUdf56(String udf56);
    public  void setUdf57(String udf57);
    public  void setUdf58(String udf58);
    public  void setUdf59(String udf59);
    public  void setUdf60(String udf60);
    public  void setUdf61(String udf61);
    public  void setUdf62(String udf62);
    public  void setUdf63(String udf63);
    public  void setUdf64(String udf64);
    public  void setUdf65(String udf65);
    public  void setUdf66(String udf66);
    public  void setUdf67(String udf67);
    public  void setUdf68(String udf68);
    public  void setUdf69(String udf69);
    public  void setUdf70(String udf70);
    public  void setUdf71(String udf71);
    public  void setUdf72(String udf72);
    public  void setUdf73(String udf73);
    public  void setUdf74(String udf74);
    public  void setUdf75(String udf75);
    public  void setUdf76(String udf76);
    public  void setUdf77(String udf77);
    public  void setUdf78(String udf78);
    public  void setUdf79(String udf79);
    public  void setUdf80(String udf80);
    public  void setUdf81(String udf81);
    public  void setUdf82(String udf82);
    public  void setUdf83(String udf83);
    public  void setUdf84(String udf84);
    public  void setUdf85(String udf85);
    public  void setUdf86(String udf86);
    public  void setUdf87(String udf87);
    public  void setUdf88(String udf88);
    public  void setUdf89(String udf89);
    public  void setUdf90(String udf90);
    public  void setUdf91(String udf91);
    public  void setUdf92(String udf92);
    public  void setUdf93(String udf93);
    public  void setUdf94(String udf94);
    public  void setUdf95(String udf95);
    public  void setUdf96(String udf96);
    public  void setUdf97(String udf97);
    public  void setUdf98(String udf98);
    public  void setUdf99(String udf99);
    public  void setUdf100(String udf100);
	public long getId();
	public void setId(long id);
	
	public long getLimitProfileId();
	public void setLimitProfileId(long limitProfileId);
	
}
