package com.integrosys.cms.app.bankingArrangementFacExclusion.bus;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.techinfra.ejbsupport.ConcurrentUpdateException;

public interface IBusManager {
	SearchResult getAll() throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IBankingArrangementFacExclusion create(IBankingArrangementFacExclusion item)throws BankingArrangementFacExclusionException;
	IBankingArrangementFacExclusion getById(long id) throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	IBankingArrangementFacExclusion update(IBankingArrangementFacExclusion item) throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IBankingArrangementFacExclusion updateToWorkingCopy(IBankingArrangementFacExclusion workingCopy, IBankingArrangementFacExclusion imageCopy) throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IBankingArrangementFacExclusion deleteToWorkingCopy(IBankingArrangementFacExclusion workingCopy, IBankingArrangementFacExclusion imageCopy) throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException,ConcurrentUpdateException;
}
