package com.integrosys.cms.app.collateralrocandinsurance.proxy;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.uiinfra.exception.CommandProcessingException;
import com.integrosys.cms.app.collateralrocandinsurance.bus.CollateralRocException;
import com.integrosys.cms.app.collateralrocandinsurance.bus.ICollateralRoc;
import com.integrosys.cms.app.collateralrocandinsurance.trx.ICollateralRocTrxValue;
import com.integrosys.cms.app.excludedfacility.bus.ExcludedFacilityException;
import com.integrosys.cms.app.transaction.ITrxContext;

public interface ICollateralRocProxyManager {

	public SearchResult getAllActualCollateralRoc() throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerCreateCollateralRoc(ITrxContext anITrxContext, ICollateralRoc anICCCollateralRoc)throws CollateralRocException,TrxParameterException,TransactionException;
	public ICollateralRocTrxValue getCollateralRocByTrxID(String aTrxID) throws CollateralRocException,TransactionException,CommandProcessingException;
	public ICollateralRocTrxValue checkerApproveCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICollateralRocTrxValue) throws CollateralRocException,TrxParameterException,TransactionException;
	public ICollateralRocTrxValue checkerRejectCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICollateralRocTrxValue) throws CollateralRocException,TrxParameterException,TransactionException;
	public ICollateralRocTrxValue getCollateralRocTrxValue(Long aCollateralRocId) throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerUpdateCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICCCollateralRocTrxValue, ICollateralRoc anICCCollateralRoc)
			throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerUpdateSaveCreateCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICCCollateralRocTrxValue, ICollateralRoc anICCCollateralRoc)
			throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerSaveCollateralRoc(ITrxContext anITrxContext, ICollateralRoc anICCCollateralRoc)throws CollateralRocException,TrxParameterException,TransactionException;
	public ICollateralRocTrxValue makerUpdateSaveUpdateCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICCCollateralRocTrxValue, ICollateralRoc anICCCollateralRoc)
			throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerEditRejectedCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICCCollateralRocTrxValue, ICollateralRoc anCollateralRoc) throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerDeleteCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICCCollateralRocTrxValue, ICollateralRoc anICCCollateralRoc)throws CollateralRocException,TrxParameterException,TransactionException;
	
	public ICollateralRocTrxValue makerCloseDraftCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICollateralRocTrxValue) throws CollateralRocException,TrxParameterException,TransactionException;
	public ICollateralRocTrxValue makerCloseRejectedCollateralRoc(ITrxContext anITrxContext, ICollateralRocTrxValue anICollateralRocTrxValue) throws CollateralRocException,TrxParameterException,TransactionException;
	
	public boolean isCollateralRocCategoryUnique(String collateralCategory,String collateralRocCode);
	
	public SearchResult getSearchedCollateralRoc(String type,String text) throws CollateralRocException,TrxParameterException,TransactionException;
}
