/*
 * Generated by XDoclet - Do not edit!
 */
package com.integrosys.cms.app.propertyindex.bus;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;

/**
 * Title: CLIMS 
 * Description: Data object for EBPropertyIdx 
 * Copyright: Integro Technologies Sdn Bhd 
 * Author: Andy Wong 
 * Date: Jan 15, 2008
 */

public class OBPropertyIdx implements IPropertyIdx {
	private long propertyIdxId;
	private java.lang.String valDescr;
    private java.lang.String countryCode;
    private long versionTime = 0;
	private Set propertyIdxSecSubTypeList;
	private Set propertyIdxItemList;
	private String status;
    private Collection propertyIdxSecSubTypeCol;

    /* begin value object */

	/* end value object */

	public OBPropertyIdx() {
	}

	public OBPropertyIdx(long propertyIdxId, java.lang.String valDescr, long versionTime) {
		setPropertyIdxId(propertyIdxId);
		setValDescr(valDescr);
		setVersionTime(versionTime);
	}

	public OBPropertyIdx(OBPropertyIdx otherData) {
		setPropertyIdxId(otherData.getPropertyIdxId());
		setValDescr(otherData.getValDescr());
		setVersionTime(otherData.getVersionTime());

	}

	public long getPropertyIdxId() {
		return this.propertyIdxId;
	}

	public void setPropertyIdxId(long propertyIdxId) {
		this.propertyIdxId = propertyIdxId;
	}

	public java.lang.String getValDescr() {
		return this.valDescr;
	}

	public void setValDescr(java.lang.String valDescr) {
		this.valDescr = valDescr;
	}

	public long getVersionTime() {
		return this.versionTime;
	}

	public void setVersionTime(long versionTime) {
		this.versionTime = versionTime;
	}

	public String toString() {
		StringBuffer str = new StringBuffer("{");

		str.append("propertyIdxId=" + getPropertyIdxId() + " " + "valDescr="
				+ getValDescr() + "versionTime=" + getVersionTime());
		str.append('}');

		return (str.toString());
	}

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

	public Set getPropertyIdxItemList() {
		return propertyIdxItemList;
	}

	public void setPropertyIdxItemList(Set propertyIdxItemList) {
		this.propertyIdxItemList = propertyIdxItemList;
	}

	public Set getPropertyIdxSecSubTypeList() {
		return propertyIdxSecSubTypeList;
	}

	public void setPropertyIdxSecSubTypeList(Set propertyIdxSecSubTypeList) {
		this.propertyIdxSecSubTypeList = propertyIdxSecSubTypeList;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

    public Collection getPropertyIdxSecSubTypeCol() {
        return new ArrayList(propertyIdxSecSubTypeList);
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null ||
            !(o instanceof OBPropertyIdx)) {
            return false;
        }

        OBPropertyIdx other = (OBPropertyIdx)o;

        // if the id is missing, return false
        if (propertyIdxId > 0) return false;

        // equivalence by id
        return propertyIdxId == other.getPropertyIdxId();
    }

    public int hashCode() {
        if (propertyIdxId > 0) {
            return Long.toString(propertyIdxId).hashCode();
        } else {
            return super.hashCode();
        }
    }
}
