package com.integrosys.cms.app.customer.bus;

import java.io.Serializable;

public interface ILimitXRefUdf extends Serializable{
	
	public String getUdf1_Label();
	public String getUdf2_Label();
	public String getUdf3_Label();
	public String getUdf4_Label();
	public String getUdf5_Label();
	public String getUdf6_Label();
	public String getUdf7_Label();
	public String getUdf8_Label();
	public String getUdf9_Label();
	public String getUdf10_Label();
	public String getUdf11_Label();
	public String getUdf12_Label();
	public String getUdf13_Label();
	public String getUdf14_Label();
	public String getUdf15_Label();
	public String getUdf16_Label();
	public String getUdf17_Label();
	public String getUdf18_Label();
	public String getUdf19_Label();
	public String getUdf20_Label();
	public String getUdf21_Label();
	public String getUdf22_Label();
	public String getUdf23_Label();
	public String getUdf24_Label();
	public String getUdf25_Label();
	public String getUdf26_Label();
	public String getUdf27_Label();
	public String getUdf28_Label();
	public String getUdf29_Label();
	public String getUdf30_Label();
	public String getUdf31_Label();
	public String getUdf32_Label();
	public String getUdf33_Label();
	public String getUdf34_Label();
	public String getUdf35_Label();
	public String getUdf36_Label();
	public String getUdf37_Label();
	public String getUdf38_Label();
	public String getUdf39_Label();
	public String getUdf40_Label();
	public String getUdf41_Label();
	public String getUdf42_Label();
	public String getUdf43_Label();
	public String getUdf44_Label();
	public String getUdf45_Label();
	public String getUdf46_Label();
	public String getUdf47_Label();
	public String getUdf48_Label();
	public String getUdf49_Label();
	public String getUdf50_Label();
    public  String getUdf51_Label();
    public  String getUdf52_Label();
    public  String getUdf53_Label();
    public  String getUdf54_Label();
    public  String getUdf55_Label();
    public  String getUdf56_Label();
    public  String getUdf57_Label();
    public  String getUdf58_Label();
    public  String getUdf59_Label();
    public  String getUdf60_Label();
    public  String getUdf61_Label();
    public  String getUdf62_Label();
    public  String getUdf63_Label();
    public  String getUdf64_Label();
    public  String getUdf65_Label();
    public  String getUdf66_Label();
    public  String getUdf67_Label();
    public  String getUdf68_Label();
    public  String getUdf69_Label();
    public  String getUdf70_Label();
    public  String getUdf71_Label();
    public  String getUdf72_Label();
    public  String getUdf73_Label();
    public  String getUdf74_Label();
    public  String getUdf75_Label();
    public  String getUdf76_Label();
    public  String getUdf77_Label();
    public  String getUdf78_Label();
    public  String getUdf79_Label();
    public  String getUdf80_Label();
    public  String getUdf81_Label();
    public  String getUdf82_Label();
    public  String getUdf83_Label();
    public  String getUdf84_Label();
    public  String getUdf85_Label();
    public  String getUdf86_Label();
    public  String getUdf87_Label();
    public  String getUdf88_Label();
    public  String getUdf89_Label();
    public  String getUdf90_Label();
    public  String getUdf91_Label();
    public  String getUdf92_Label();
    public  String getUdf93_Label();
    public  String getUdf94_Label();
    public  String getUdf95_Label();
    public  String getUdf96_Label();
    public  String getUdf97_Label();
    public  String getUdf98_Label();
    public  String getUdf99_Label();
    public  String getUdf100_Label();
    
    public String getUdf101_Label();
    public String getUdf102_Label();
    public String getUdf103_Label();
    public String getUdf104_Label();
    public String getUdf105_Label();
    public String getUdf106_Label();
    public String getUdf107_Label();
    public String getUdf108_Label();
    public String getUdf109_Label();
    public String getUdf110_Label();
    public String getUdf111_Label();
    public String getUdf112_Label();
    public String getUdf113_Label();
    public String getUdf114_Label();
    public String getUdf115_Label();
   
    public String getUdf1_Value();
	public String getUdf2_Value();
	public String getUdf3_Value();
	public String getUdf4_Value();
	public String getUdf5_Value();
	public String getUdf6_Value();
	public String getUdf7_Value();
	public String getUdf8_Value();
	public String getUdf9_Value();
	public String getUdf10_Value();
	public String getUdf11_Value();
	public String getUdf12_Value();
	public String getUdf13_Value();
	public String getUdf14_Value();
	public String getUdf15_Value();
	public String getUdf16_Value();
	public String getUdf17_Value();
	public String getUdf18_Value();
	public String getUdf19_Value();
	public String getUdf20_Value();
	public String getUdf21_Value();
	public String getUdf22_Value();
	public String getUdf23_Value();
	public String getUdf24_Value();
	public String getUdf25_Value();
	public String getUdf26_Value();
	public String getUdf27_Value();
	public String getUdf28_Value();
	public String getUdf29_Value();
	public String getUdf30_Value();
	public String getUdf31_Value();
	public String getUdf32_Value();
	public String getUdf33_Value();
	public String getUdf34_Value();
	public String getUdf35_Value();
	public String getUdf36_Value();
	public String getUdf37_Value();
	public String getUdf38_Value();
	public String getUdf39_Value();
	public String getUdf40_Value();
	public String getUdf41_Value();
	public String getUdf42_Value();
	public String getUdf43_Value();
	public String getUdf44_Value();
	public String getUdf45_Value();
	public String getUdf46_Value();
	public String getUdf47_Value();
	public String getUdf48_Value();
	public String getUdf49_Value();
	public String getUdf50_Value();
    public  String getUdf51_Value();
    public  String getUdf52_Value();
    public  String getUdf53_Value();
    public  String getUdf54_Value();
    public  String getUdf55_Value();
    public  String getUdf56_Value();
    public  String getUdf57_Value();
    public  String getUdf58_Value();
    public  String getUdf59_Value();
    public  String getUdf60_Value();
    public  String getUdf61_Value();
    public  String getUdf62_Value();
    public  String getUdf63_Value();
    public  String getUdf64_Value();
    public  String getUdf65_Value();
    public  String getUdf66_Value();
    public  String getUdf67_Value();
    public  String getUdf68_Value();
    public  String getUdf69_Value();
    public  String getUdf70_Value();
    public  String getUdf71_Value();
    public  String getUdf72_Value();
    public  String getUdf73_Value();
    public  String getUdf74_Value();
    public  String getUdf75_Value();
    public  String getUdf76_Value();
    public  String getUdf77_Value();
    public  String getUdf78_Value();
    public  String getUdf79_Value();
    public  String getUdf80_Value();
    public  String getUdf81_Value();
    public  String getUdf82_Value();
    public  String getUdf83_Value();
    public  String getUdf84_Value();
    public  String getUdf85_Value();
    public  String getUdf86_Value();
    public  String getUdf87_Value();
    public  String getUdf88_Value();
    public  String getUdf89_Value();
    public  String getUdf90_Value();
    public  String getUdf91_Value();
    public  String getUdf92_Value();
    public  String getUdf93_Value();
    public  String getUdf94_Value();
    public  String getUdf95_Value();
    public  String getUdf96_Value();
    public  String getUdf97_Value();
    public  String getUdf98_Value();
    public  String getUdf99_Value();
    public  String getUdf100_Value();
    
     public  String getUdf101_Value();
    public  String getUdf102_Value();
    public  String getUdf103_Value();
    public  String getUdf104_Value();
    public  String getUdf105_Value();
    public String getUdf106_Value();
    public String getUdf107_Value();
    public String getUdf108_Value();
    public String getUdf109_Value();
    public String getUdf110_Value();
    public String getUdf111_Value();
    public String getUdf112_Value();
    public String getUdf113_Value();
    public String getUdf114_Value();
    public String getUdf115_Value();
    
	public String getUdf1_Flag();
	public String getUdf2_Flag();
	public String getUdf3_Flag();
	public String getUdf4_Flag();
	public String getUdf5_Flag();
	public String getUdf6_Flag();
	public String getUdf7_Flag();
	public String getUdf8_Flag();
	public String getUdf9_Flag();
	public String getUdf10_Flag();
	public String getUdf11_Flag();
	public String getUdf12_Flag();
	public String getUdf13_Flag();
	public String getUdf14_Flag();
	public String getUdf15_Flag();
	public String getUdf16_Flag();
	public String getUdf17_Flag();
	public String getUdf18_Flag();
	public String getUdf19_Flag();
	public String getUdf20_Flag();
	public String getUdf21_Flag();
	public String getUdf22_Flag();
	public String getUdf23_Flag();
	public String getUdf24_Flag();
	public String getUdf25_Flag();
	public String getUdf26_Flag();
	public String getUdf27_Flag();
	public String getUdf28_Flag();
	public String getUdf29_Flag();
	public String getUdf30_Flag();
	public String getUdf31_Flag();
	public String getUdf32_Flag();
	public String getUdf33_Flag();
	public String getUdf34_Flag();
	public String getUdf35_Flag();
	public String getUdf36_Flag();
	public String getUdf37_Flag();
	public String getUdf38_Flag();
	public String getUdf39_Flag();
	public String getUdf40_Flag();
	public String getUdf41_Flag();
	public String getUdf42_Flag();
	public String getUdf43_Flag();
	public String getUdf44_Flag();
	public String getUdf45_Flag();
	public String getUdf46_Flag();
	public String getUdf47_Flag();
	public String getUdf48_Flag();
	public String getUdf49_Flag();
	public String getUdf50_Flag();
    public  String getUdf51_Flag();
    public  String getUdf52_Flag();
    public  String getUdf53_Flag();
    public  String getUdf54_Flag();
    public  String getUdf55_Flag();
    public  String getUdf56_Flag();
    public  String getUdf57_Flag();
    public  String getUdf58_Flag();
    public  String getUdf59_Flag();
    public  String getUdf60_Flag();
    public  String getUdf61_Flag();
    public  String getUdf62_Flag();
    public  String getUdf63_Flag();
    public  String getUdf64_Flag();
    public  String getUdf65_Flag();
    public  String getUdf66_Flag();
    public  String getUdf67_Flag();
    public  String getUdf68_Flag();
    public  String getUdf69_Flag();
    public  String getUdf70_Flag();
    public  String getUdf71_Flag();
    public  String getUdf72_Flag();
    public  String getUdf73_Flag();
    public  String getUdf74_Flag();
    public  String getUdf75_Flag();
    public  String getUdf76_Flag();
    public  String getUdf77_Flag();
    public  String getUdf78_Flag();
    public  String getUdf79_Flag();
    public  String getUdf80_Flag();
    public  String getUdf81_Flag();
    public  String getUdf82_Flag();
    public  String getUdf83_Flag();
    public  String getUdf84_Flag();
    public  String getUdf85_Flag();
    public  String getUdf86_Flag();
    public  String getUdf87_Flag();
    public  String getUdf88_Flag();
    public  String getUdf89_Flag();
    public  String getUdf90_Flag();
    public  String getUdf91_Flag();
    public  String getUdf92_Flag();
    public  String getUdf93_Flag();
    public  String getUdf94_Flag();
    public  String getUdf95_Flag();
    public  String getUdf96_Flag();
    public  String getUdf97_Flag();
    public  String getUdf98_Flag();
    public  String getUdf99_Flag();
    public  String getUdf100_Flag();
    
    public  String getUdf101_Flag();
    public  String getUdf102_Flag();
    public  String getUdf103_Flag();
    public  String getUdf104_Flag();
    public  String getUdf105_Flag();
    public String getUdf106_Flag();
    public String getUdf107_Flag();
    public String getUdf108_Flag();
    public String getUdf109_Flag();
    public String getUdf110_Flag();
    public String getUdf111_Flag();
    public String getUdf112_Flag();
    public String getUdf113_Flag();
    public String getUdf114_Flag();
    public String getUdf115_Flag();
   
   
    public void setUdf1_Label(String udf_Label);
	public void setUdf2_Label(String udf_Label);
	public void setUdf3_Label(String udf_Label);
	public void setUdf4_Label(String udf_Label);
	public void setUdf5_Label(String udf_Label);
	public void setUdf6_Label(String udf_Label);
	public void setUdf7_Label(String udf_Label);
	public void setUdf8_Label(String udf_Label);
	public void setUdf9_Label(String udf_Label);
	public void setUdf10_Label(String udf_Label);
	public void setUdf11_Label(String udf_Label);
	public void setUdf12_Label(String udf_Label);
	public void setUdf13_Label(String udf_Label);
	public void setUdf14_Label(String udf_Label);
	public void setUdf15_Label(String udf_Label);
	public void setUdf16_Label(String udf_Label);
	public void setUdf17_Label(String udf_Label);
	public void setUdf18_Label(String udf_Label);
	public void setUdf19_Label(String udf_Label);
	public void setUdf20_Label(String udf_Label);
	public void setUdf21_Label(String udf_Label);
	public void setUdf22_Label(String udf_Label);
	public void setUdf23_Label(String udf_Label);
	public void setUdf24_Label(String udf_Label);
	public void setUdf25_Label(String udf_Label);
	public void setUdf26_Label(String udf_Label);
	public void setUdf27_Label(String udf_Label);
	public void setUdf28_Label(String udf_Label);
	public void setUdf29_Label(String udf_Label);
	public void setUdf30_Label(String udf_Label);
	public void setUdf31_Label(String udf_Label);
	public void setUdf32_Label(String udf_Label);
	public void setUdf33_Label(String udf_Label);
	public void setUdf34_Label(String udf_Label);
	public void setUdf35_Label(String udf_Label);
	public void setUdf36_Label(String udf_Label);
	public void setUdf37_Label(String udf_Label);
	public void setUdf38_Label(String udf_Label);
	public void setUdf39_Label(String udf_Label);
	public void setUdf40_Label(String udf_Label);
	public void setUdf41_Label(String udf_Label);
	public void setUdf42_Label(String udf_Label);
	public void setUdf43_Label(String udf_Label);
	public void setUdf44_Label(String udf_Label);
	public void setUdf45_Label(String udf_Label);
	public void setUdf46_Label(String udf_Label);
	public void setUdf47_Label(String udf_Label);
	public void setUdf48_Label(String udf_Label);
	public void setUdf49_Label(String udf_Label);
	public void setUdf50_Label(String udf_Label);
    public  void setUdf51_Label(String udf51_Label);
    public  void setUdf52_Label(String udf52_Label);
    public  void setUdf53_Label(String udf53_Label);
    public  void setUdf54_Label(String udf54_Label);
    public  void setUdf55_Label(String udf55_Label);
    public  void setUdf56_Label(String udf56_Label);
    public  void setUdf57_Label(String udf57_Label);
    public  void setUdf58_Label(String udf58_Label);
    public  void setUdf59_Label(String udf59_Label);
    public  void setUdf60_Label(String udf60_Label);
    public  void setUdf61_Label(String udf61_Label);
    public  void setUdf62_Label(String udf62_Label);
    public  void setUdf63_Label(String udf63_Label);
    public  void setUdf64_Label(String udf64_Label);
    public  void setUdf65_Label(String udf65_Label);
    public  void setUdf66_Label(String udf66_Label);
    public  void setUdf67_Label(String udf67_Label);
    public  void setUdf68_Label(String udf68_Label);
    public  void setUdf69_Label(String udf69_Label);
    public  void setUdf70_Label(String udf70_Label);
    public  void setUdf71_Label(String udf71_Label);
    public  void setUdf72_Label(String udf72_Label);
    public  void setUdf73_Label(String udf73_Label);
    public  void setUdf74_Label(String udf74_Label);
    public  void setUdf75_Label(String udf75_Label);
    public  void setUdf76_Label(String udf76_Label);
    public  void setUdf77_Label(String udf77_Label);
    public  void setUdf78_Label(String udf78_Label);
    public  void setUdf79_Label(String udf79_Label);
    public  void setUdf80_Label(String udf80_Label);
    public  void setUdf81_Label(String udf81_Label);
    public  void setUdf82_Label(String udf82_Label);
    public  void setUdf83_Label(String udf83_Label);
    public  void setUdf84_Label(String udf84_Label);
    public  void setUdf85_Label(String udf85_Label);
    public  void setUdf86_Label(String udf86_Label);
    public  void setUdf87_Label(String udf87_Label);
    public  void setUdf88_Label(String udf88_Label);
    public  void setUdf89_Label(String udf89_Label);
    public  void setUdf90_Label(String udf90_Label);
    public  void setUdf91_Label(String udf91_Label);
    public  void setUdf92_Label(String udf92_Label);
    public  void setUdf93_Label(String udf93_Label);
    public  void setUdf94_Label(String udf94_Label);
    public  void setUdf95_Label(String udf95_Label);
    public  void setUdf96_Label(String udf96_Label);
    public  void setUdf97_Label(String udf97_Label);
    public  void setUdf98_Label(String udf98_Label);
    public  void setUdf99_Label(String udf99_Label);
    public  void setUdf100_Label(String udf100_Label);
    
    public  void setUdf101_Label(String udf101_Label);
    public  void setUdf102_Label(String udf102_Label);
    public  void setUdf103_Label(String udf103_Label);
    public  void setUdf104_Label(String udf104_Label);
    public  void setUdf105_Label(String udf105_Label);
    public  void setUdf106_Label(String udf106_Label);
    public void setUdf107_Label(String udf107_Label); 
    public void setUdf108_Label(String udf108_Label);
    public void setUdf109_Label(String udf109_Label);
    public void setUdf110_Label(String udf110_Label);
    public void setUdf111_Label(String udf111_Label);
    public void setUdf112_Label(String udf112_Label);
    public void setUdf113_Label(String udf113_Label);
    public void setUdf114_Label(String udf114_Label);
    public void setUdf115_Label(String udf115_Label);
 
    public void setUdf1_Value(String udf_Value);
	public void setUdf2_Value(String udf_Value);
	public void setUdf3_Value(String udf_Value);
	public void setUdf4_Value(String udf_Value);
	public void setUdf5_Value(String udf_Value);
	public void setUdf6_Value(String udf_Value);
	public void setUdf7_Value(String udf_Value);
	public void setUdf8_Value(String udf_Value);
	public void setUdf9_Value(String udf_Value);
	public void setUdf10_Value(String udf_Value);
	public void setUdf11_Value(String udf_Value);
	public void setUdf12_Value(String udf_Value);
	public void setUdf13_Value(String udf_Value);
	public void setUdf14_Value(String udf_Value);
	public void setUdf15_Value(String udf_Value);
	public void setUdf16_Value(String udf_Value);
	public void setUdf17_Value(String udf_Value);
	public void setUdf18_Value(String udf_Value);
	public void setUdf19_Value(String udf_Value);
	public void setUdf20_Value(String udf_Value);
	public void setUdf21_Value(String udf_Value);
	public void setUdf22_Value(String udf_Value);
	public void setUdf23_Value(String udf_Value);
	public void setUdf24_Value(String udf_Value);
	public void setUdf25_Value(String udf_Value);
	public void setUdf26_Value(String udf_Value);
	public void setUdf27_Value(String udf_Value);
	public void setUdf28_Value(String udf_Value);
	public void setUdf29_Value(String udf_Value);
	public void setUdf30_Value(String udf_Value);
	public void setUdf31_Value(String udf_Value);
	public void setUdf32_Value(String udf_Value);
	public void setUdf33_Value(String udf_Value);
	public void setUdf34_Value(String udf_Value);
	public void setUdf35_Value(String udf_Value);
	public void setUdf36_Value(String udf_Value);
	public void setUdf37_Value(String udf_Value);
	public void setUdf38_Value(String udf_Value);
	public void setUdf39_Value(String udf_Value);
	public void setUdf40_Value(String udf_Value);
	public void setUdf41_Value(String udf_Value);
	public void setUdf42_Value(String udf_Value);
	public void setUdf43_Value(String udf_Value);
	public void setUdf44_Value(String udf_Value);
	public void setUdf45_Value(String udf_Value);
	public void setUdf46_Value(String udf_Value);
	public void setUdf47_Value(String udf_Value);
	public void setUdf48_Value(String udf_Value);
	public void setUdf49_Value(String udf_Value);
	public void setUdf50_Value(String udf_Value);
    public  void setUdf51_Value(String udf51_Value);
    public  void setUdf52_Value(String udf52_Value);
    public  void setUdf53_Value(String udf53_Value);
    public  void setUdf54_Value(String udf54_Value);
    public  void setUdf55_Value(String udf55_Value);
    public  void setUdf56_Value(String udf56_Value);
    public  void setUdf57_Value(String udf57_Value);
    public  void setUdf58_Value(String udf58_Value);
    public  void setUdf59_Value(String udf59_Value);
    public  void setUdf60_Value(String udf60_Value);
    public  void setUdf61_Value(String udf61_Value);
    public  void setUdf62_Value(String udf62_Value);
    public  void setUdf63_Value(String udf63_Value);
    public  void setUdf64_Value(String udf64_Value);
    public  void setUdf65_Value(String udf65_Value);
    public  void setUdf66_Value(String udf66_Value);
    public  void setUdf67_Value(String udf67_Value);
    public  void setUdf68_Value(String udf68_Value);
    public  void setUdf69_Value(String udf69_Value);
    public  void setUdf70_Value(String udf70_Value);
    public  void setUdf71_Value(String udf71_Value);
    public  void setUdf72_Value(String udf72_Value);
    public  void setUdf73_Value(String udf73_Value);
    public  void setUdf74_Value(String udf74_Value);
    public  void setUdf75_Value(String udf75_Value);
    public  void setUdf76_Value(String udf76_Value);
    public  void setUdf77_Value(String udf77_Value);
    public  void setUdf78_Value(String udf78_Value);
    public  void setUdf79_Value(String udf79_Value);
    public  void setUdf80_Value(String udf80_Value);
    public  void setUdf81_Value(String udf81_Value);
    public  void setUdf82_Value(String udf82_Value);
    public  void setUdf83_Value(String udf83_Value);
    public  void setUdf84_Value(String udf84_Value);
    public  void setUdf85_Value(String udf85_Value);
    public  void setUdf86_Value(String udf86_Value);
    public  void setUdf87_Value(String udf87_Value);
    public  void setUdf88_Value(String udf88_Value);
    public  void setUdf89_Value(String udf89_Value);
    public  void setUdf90_Value(String udf90_Value);
    public  void setUdf91_Value(String udf91_Value);
    public  void setUdf92_Value(String udf92_Value);
    public  void setUdf93_Value(String udf93_Value);
    public  void setUdf94_Value(String udf94_Value);
    public  void setUdf95_Value(String udf95_Value);
    public  void setUdf96_Value(String udf96_Value);
    public  void setUdf97_Value(String udf97_Value);
    public  void setUdf98_Value(String udf98_Value);
    public  void setUdf99_Value(String udf99_Value);
    public  void setUdf100_Value(String udf100_Value);
    
    public  void setUdf101_Value(String udf101_Value);
    public  void setUdf102_Value(String udf102_Value);
    public  void setUdf103_Value(String udf103_Value);
    public  void setUdf104_Value(String udf104_Value);
    public  void setUdf105_Value(String udf105_Value);
    public void setUdf106_Value(String udf106_Value);
    public void setUdf107_Value(String udf107_Value); 
    public void setUdf108_Value(String udf108_Value);
    public void setUdf109_Value(String udf109_Value);
    public void setUdf110_Value(String udf110_Value);
    public void setUdf111_Value(String udf111_Value);
    public void setUdf112_Value(String udf112_Value);
    public void setUdf113_Value(String udf113_Value);
    public void setUdf114_Value(String udf114_Value);
    public void setUdf115_Value(String udf115_Value);
 
    
    public void setUdf1_Flag(String udf_Flag);
	public void setUdf2_Flag(String udf_Flag);
	public void setUdf3_Flag(String udf_Flag);
	public void setUdf4_Flag(String udf_Flag);
	public void setUdf5_Flag(String udf_Flag);
	public void setUdf6_Flag(String udf_Flag);
	public void setUdf7_Flag(String udf_Flag);
	public void setUdf8_Flag(String udf_Flag);
	public void setUdf9_Flag(String udf_Flag);
	public void setUdf10_Flag(String udf_Flag);
	public void setUdf11_Flag(String udf_Flag);
	public void setUdf12_Flag(String udf_Flag);
	public void setUdf13_Flag(String udf_Flag);
	public void setUdf14_Flag(String udf_Flag);
	public void setUdf15_Flag(String udf_Flag);
	public void setUdf16_Flag(String udf_Flag);
	public void setUdf17_Flag(String udf_Flag);
	public void setUdf18_Flag(String udf_Flag);
	public void setUdf19_Flag(String udf_Flag);
	public void setUdf20_Flag(String udf_Flag);
	public void setUdf21_Flag(String udf_Flag);
	public void setUdf22_Flag(String udf_Flag);
	public void setUdf23_Flag(String udf_Flag);
	public void setUdf24_Flag(String udf_Flag);
	public void setUdf25_Flag(String udf_Flag);
	public void setUdf26_Flag(String udf_Flag);
	public void setUdf27_Flag(String udf_Flag);
	public void setUdf28_Flag(String udf_Flag);
	public void setUdf29_Flag(String udf_Flag);
	public void setUdf30_Flag(String udf_Flag);
	public void setUdf31_Flag(String udf_Flag);
	public void setUdf32_Flag(String udf_Flag);
	public void setUdf33_Flag(String udf_Flag);
	public void setUdf34_Flag(String udf_Flag);
	public void setUdf35_Flag(String udf_Flag);
	public void setUdf36_Flag(String udf_Flag);
	public void setUdf37_Flag(String udf_Flag);
	public void setUdf38_Flag(String udf_Flag);
	public void setUdf39_Flag(String udf_Flag);
	public void setUdf40_Flag(String udf_Flag);
	public void setUdf41_Flag(String udf_Flag);
	public void setUdf42_Flag(String udf_Flag);
	public void setUdf43_Flag(String udf_Flag);
	public void setUdf44_Flag(String udf_Flag);
	public void setUdf45_Flag(String udf_Flag);
	public void setUdf46_Flag(String udf_Flag);
	public void setUdf47_Flag(String udf_Flag);
	public void setUdf48_Flag(String udf_Flag);
	public void setUdf49_Flag(String udf_Flag);
	public void setUdf50_Flag(String udf_Flag);
    public  void setUdf51_Flag(String udf51_Flag);
    public  void setUdf52_Flag(String udf52_Flag);
    public  void setUdf53_Flag(String udf53_Flag);
    public  void setUdf54_Flag(String udf54_Flag);
    public  void setUdf55_Flag(String udf55_Flag);
    public  void setUdf56_Flag(String udf56_Flag);
    public  void setUdf57_Flag(String udf57_Flag);
    public  void setUdf58_Flag(String udf58_Flag);
    public  void setUdf59_Flag(String udf59_Flag);
    public  void setUdf60_Flag(String udf60_Flag);
    public  void setUdf61_Flag(String udf61_Flag);
    public  void setUdf62_Flag(String udf62_Flag);
    public  void setUdf63_Flag(String udf63_Flag);
    public  void setUdf64_Flag(String udf64_Flag);
    public  void setUdf65_Flag(String udf65_Flag);
    public  void setUdf66_Flag(String udf66_Flag);
    public  void setUdf67_Flag(String udf67_Flag);
    public  void setUdf68_Flag(String udf68_Flag);
    public  void setUdf69_Flag(String udf69_Flag);
    public  void setUdf70_Flag(String udf70_Flag);
    public  void setUdf71_Flag(String udf71_Flag);
    public  void setUdf72_Flag(String udf72_Flag);
    public  void setUdf73_Flag(String udf73_Flag);
    public  void setUdf74_Flag(String udf74_Flag);
    public  void setUdf75_Flag(String udf75_Flag);
    public  void setUdf76_Flag(String udf76_Flag);
    public  void setUdf77_Flag(String udf77_Flag);
    public  void setUdf78_Flag(String udf78_Flag);
    public  void setUdf79_Flag(String udf79_Flag);
    public  void setUdf80_Flag(String udf80_Flag);
    public  void setUdf81_Flag(String udf81_Flag);
    public  void setUdf82_Flag(String udf82_Flag);
    public  void setUdf83_Flag(String udf83_Flag);
    public  void setUdf84_Flag(String udf84_Flag);
    public  void setUdf85_Flag(String udf85_Flag);
    public  void setUdf86_Flag(String udf86_Flag);
    public  void setUdf87_Flag(String udf87_Flag);
    public  void setUdf88_Flag(String udf88_Flag);
    public  void setUdf89_Flag(String udf89_Flag);
    public  void setUdf90_Flag(String udf90_Flag);
    public  void setUdf91_Flag(String udf91_Flag);
    public  void setUdf92_Flag(String udf92_Flag);
    public  void setUdf93_Flag(String udf93_Flag);
    public  void setUdf94_Flag(String udf94_Flag);
    public  void setUdf95_Flag(String udf95_Flag);
    public  void setUdf96_Flag(String udf96_Flag);
    public  void setUdf97_Flag(String udf97_Flag);
    public  void setUdf98_Flag(String udf98_Flag);
    public  void setUdf99_Flag(String udf99_Flag);
    public  void setUdf100_Flag(String udf100_Flag);
      
    public  void setUdf101_Flag(String udf101_Flag);
    public  void setUdf102_Flag(String udf102_Flag);
    public  void setUdf103_Flag(String udf103_Flag);
    public  void setUdf104_Flag(String udf104_Flag);
    public  void setUdf105_Flag(String udf105_Flag);
    public  void setUdf106_Flag(String udf106_Flag);
    public void setUdf107_Flag(String udf107_Flag); 
    public void setUdf108_Flag(String udf108_Flag);
    public void setUdf109_Flag(String udf109_Flag);
    public void setUdf110_Flag(String udf110_Flag);
    public void setUdf111_Flag(String udf111_Flag);
    public void setUdf112_Flag(String udf112_Flag);
    public void setUdf113_Flag(String udf113_Flag);
    public void setUdf114_Flag(String udf114_Flag);
    public void setUdf115_Flag(String udf115_Flag);
  
	public long getId();
	public void setId(long id);
	
	public long getXRefID();
	public void setXRefID(long xrefID);
}
