package com.integrosys.cms.ui.udf;

public interface IUserExtendable {
	public String getUdf1();
	public String getUdf2();
	public String getUdf3();
	public String getUdf4();
	public String getUdf5();
	public String getUdf6();
	public String getUdf7();
	public String getUdf8();
	public String getUdf9();
	public String getUdf10();
	public String getUdf11();
	public String getUdf12();
	public String getUdf13();
	public String getUdf14();
	public String getUdf15();
	public String getUdf16();
	public String getUdf17();
	public String getUdf18();
	public String getUdf19();
	public String getUdf20();
	public String getUdf21();
	public String getUdf22();
	public String getUdf23();
	public String getUdf24();
	public String getUdf25();
	public String getUdf26();
	public String getUdf27();
	public String getUdf28();
	public String getUdf29();
	public String getUdf30();
	public String getUdf31();
	public String getUdf32();
	public String getUdf33();
	public String getUdf34();
	public String getUdf35();
	public String getUdf36();
	public String getUdf37();
	public String getUdf38();
	public String getUdf39();
	public String getUdf40();
	public String getUdf41();
	public String getUdf42();
	public String getUdf43();
	public String getUdf44();
	public String getUdf45();
	public String getUdf46();
	public String getUdf47();
	public String getUdf48();
	public String getUdf49();
	public String getUdf50();
	public void setUdf1(String udf);
	public void setUdf2(String udf);
	public void setUdf3(String udf);
	public void setUdf4(String udf);
	public void setUdf5(String udf);
	public void setUdf6(String udf);
	public void setUdf7(String udf);
	public void setUdf8(String udf);
	public void setUdf9(String udf);
	public void setUdf10(String udf);
	public void setUdf11(String udf);
	public void setUdf12(String udf);
	public void setUdf13(String udf);
	public void setUdf14(String udf);
	public void setUdf15(String udf);
	public void setUdf16(String udf);
	public void setUdf17(String udf);
	public void setUdf18(String udf);
	public void setUdf19(String udf);
	public void setUdf20(String udf);
	public void setUdf21(String udf);
	public void setUdf22(String udf);
	public void setUdf23(String udf);
	public void setUdf24(String udf);
	public void setUdf25(String udf);
	public void setUdf26(String udf);
	public void setUdf27(String udf);
	public void setUdf28(String udf);
	public void setUdf29(String udf);
	public void setUdf30(String udf);
	public void setUdf31(String udf);
	public void setUdf32(String udf);
	public void setUdf33(String udf);
	public void setUdf34(String udf);
	public void setUdf35(String udf);
	public void setUdf36(String udf);
	public void setUdf37(String udf);
	public void setUdf38(String udf);
	public void setUdf39(String udf);
	public void setUdf40(String udf);
	public void setUdf41(String udf);
	public void setUdf42(String udf);
	public void setUdf43(String udf);
	public void setUdf44(String udf);
	public void setUdf45(String udf);
	public void setUdf46(String udf);
	public void setUdf47(String udf);
	public void setUdf48(String udf);
	public void setUdf49(String udf);
	public void setUdf50(String udf);
    public  String getUdf51();
    public  String getUdf52();
    public  String getUdf53();
    public  String getUdf54();
    public  String getUdf55();
    public  String getUdf56();
    public  String getUdf57();
    public  String getUdf58();
    public  String getUdf59();
    public  String getUdf60();
    public  String getUdf61();
    public  String getUdf62();
    public  String getUdf63();
    public  String getUdf64();
    public  String getUdf65();
    public  String getUdf66();
    public  String getUdf67();
    public  String getUdf68();
    public  String getUdf69();
    public  String getUdf70();
    public  String getUdf71();
    public  String getUdf72();
    public  String getUdf73();
    public  String getUdf74();
    public  String getUdf75();
    public  String getUdf76();
    public  String getUdf77();
    public  String getUdf78();
    public  String getUdf79();
    public  String getUdf80();
    public  String getUdf81();
    public  String getUdf82();
    public  String getUdf83();
    public  String getUdf84();
    public  String getUdf85();
    public  String getUdf86();
    public  String getUdf87();
    public  String getUdf88();
    public  String getUdf89();
    public  String getUdf90();
    public  String getUdf91();
    public  String getUdf92();
    public  String getUdf93();
    public  String getUdf94();
    public  String getUdf95();
    public  String getUdf96();
    public  String getUdf97();
    public  String getUdf98();
    public  String getUdf99();
    public  String getUdf100();
    
    public  String getUdf101();
    public  String getUdf102();
    public  String getUdf103();
    public  String getUdf104();
    public String getUdf105();
    public String getUdf106();
    public String getUdf107();
    public String getUdf108();
    public String getUdf109();
    public String getUdf110();
    public String getUdf111();
    public String getUdf112();
    public String getUdf113();
    public String getUdf114();
    public String getUdf115();
   
    public  void setUdf51(String udf51);
    public  void setUdf52(String udf52);
    public  void setUdf53(String udf53);
    public  void setUdf54(String udf54);
    public  void setUdf55(String udf55);
    public  void setUdf56(String udf56);
    public  void setUdf57(String udf57);
    public  void setUdf58(String udf58);
    public  void setUdf59(String udf59);
    public  void setUdf60(String udf60);
    public  void setUdf61(String udf61);
    public  void setUdf62(String udf62);
    public  void setUdf63(String udf63);
    public  void setUdf64(String udf64);
    public  void setUdf65(String udf65);
    public  void setUdf66(String udf66);
    public  void setUdf67(String udf67);
    public  void setUdf68(String udf68);
    public  void setUdf69(String udf69);
    public  void setUdf70(String udf70);
    public  void setUdf71(String udf71);
    public  void setUdf72(String udf72);
    public  void setUdf73(String udf73);
    public  void setUdf74(String udf74);
    public  void setUdf75(String udf75);
    public  void setUdf76(String udf76);
    public  void setUdf77(String udf77);
    public  void setUdf78(String udf78);
    public  void setUdf79(String udf79);
    public  void setUdf80(String udf80);
    public  void setUdf81(String udf81);
    public  void setUdf82(String udf82);
    public  void setUdf83(String udf83);
    public  void setUdf84(String udf84);
    public  void setUdf85(String udf85);
    public  void setUdf86(String udf86);
    public  void setUdf87(String udf87);
    public  void setUdf88(String udf88);
    public  void setUdf89(String udf89);
    public  void setUdf90(String udf90);
    public  void setUdf91(String udf91);
    public  void setUdf92(String udf92);
    public  void setUdf93(String udf93);
    public  void setUdf94(String udf94);
    public  void setUdf95(String udf95);
    public  void setUdf96(String udf96);
    public  void setUdf97(String udf97);
    public  void setUdf98(String udf98);
    public  void setUdf99(String udf99);
    public  void setUdf100(String udf100);
    
    public  void setUdf101(String udf101);
    public  void setUdf102(String udf102);
    public  void setUdf103(String udf103);
    public  void setUdf104(String udf104);
    public  void setUdf105(String udf105);
    public  void setUdf106(String udf106);
	public  void setUdf107(String udf107); 
	public  void setUdf108(String udf108);
	public  void setUdf109(String udf109);
	public  void setUdf110(String udf110);
	public  void setUdf111(String udf111);
	public  void setUdf112(String udf112);
	public  void setUdf113(String udf113);
	public  void setUdf114(String udf114);
	public  void setUdf115(String udf115);
	
	
	public String getUdf116();
	public String getUdf117();
	public String getUdf118();
	public String getUdf119();
	public String getUdf120();
	public String getUdf121();
	public String getUdf122();
	public String getUdf123();
	public String getUdf124();
	public String getUdf125();
	public String getUdf126();
	public String getUdf127();
	public String getUdf128();
	public String getUdf129();
	public String getUdf130();
	public String getUdf131();
	public String getUdf132();
	public String getUdf133();
	public String getUdf134();
	public String getUdf135();
	public String getUdf136();
	public String getUdf137();
	public String getUdf138();
	public String getUdf139();
	public String getUdf140();
	public String getUdf141();
	public String getUdf142();
	public String getUdf143();
	public String getUdf144();
	public String getUdf145();
	public String getUdf146();
	public String getUdf147();
	public String getUdf148();
	public String getUdf149();
	public String getUdf150();
	public  String getUdf151();
    
    public  String getUdf152();
    public  String getUdf153();
    public  String getUdf154();
    public  String getUdf155();
    public  String getUdf156();
    public  String getUdf157();
    public  String getUdf158();
    public  String getUdf159();
    public  String getUdf160();
    public  String getUdf161();
    public  String getUdf162();
    public  String getUdf163();
    public  String getUdf164();
    public  String getUdf165();
    public  String getUdf166();
    public  String getUdf167();
    public  String getUdf168();
    public  String getUdf169();
    public  String getUdf170();
    public  String getUdf171();
    public  String getUdf172();
    public  String getUdf173();
    public  String getUdf174();
    public  String getUdf175();
    public  String getUdf176();
    public  String getUdf177();
    public  String getUdf178();
    public  String getUdf179();
    public  String getUdf180();
    public  String getUdf181();
    public  String getUdf182();
    public  String getUdf183();
    public  String getUdf184();
    public  String getUdf185();
    public  String getUdf186();
    public  String getUdf187();
    public  String getUdf188();
    public  String getUdf189();
    public  String getUdf190();
    public  String getUdf191();
    public  String getUdf192();
    public  String getUdf193();
    public  String getUdf194();
    public  String getUdf195();
    public  String getUdf196();
    public  String getUdf197();
    public  String getUdf198();
    public  String getUdf199();
    public  String getUdf200();

     public String getUdf201();
	public String getUdf202();
	public String getUdf203();
	public String getUdf204();
	public String getUdf205();
	public String getUdf206();
	public String getUdf207();
	public String getUdf208();
	public String getUdf209();
	public String getUdf210();
	public String getUdf211();
	public String getUdf212();
	public String getUdf213();
	public String getUdf214();
	public String getUdf215();
	
    
	
	
	public void setUdf116(String udf);
	public void setUdf117(String udf);
	public void setUdf118(String udf);
	public void setUdf119(String udf);
	public void setUdf120(String udf);
	public void setUdf121(String udf);
	public void setUdf122(String udf);
	public void setUdf123(String udf);
	public void setUdf124(String udf);
	public void setUdf125(String udf);
	public void setUdf126(String udf);
	public void setUdf127(String udf);
	public void setUdf128(String udf);
	public void setUdf129(String udf);
	public void setUdf130(String udf);
	public void setUdf131(String udf);
	public void setUdf132(String udf);
	public void setUdf133(String udf);
	public void setUdf134(String udf);
	public void setUdf135(String udf);
	public void setUdf136(String udf);
	public void setUdf137(String udf);
	public void setUdf138(String udf);
	public void setUdf139(String udf);
	public void setUdf140(String udf);
	public void setUdf141(String udf);
	public void setUdf142(String udf);
	public void setUdf143(String udf);
	public void setUdf144(String udf);
	public void setUdf145(String udf);
	public void setUdf146(String udf);
	public void setUdf147(String udf);
	public void setUdf148(String udf);
	public void setUdf149(String udf);
	public void setUdf150(String udf);

    public  void setUdf151(String udf151);
    public  void setUdf152(String udf152);
    public  void setUdf153(String udf153);
    public  void setUdf154(String udf154);
    public  void setUdf155(String udf155);
    public  void setUdf156(String udf156);
    public  void setUdf157(String udf157);
    public  void setUdf158(String udf158);
    public  void setUdf159(String udf159);
    public  void setUdf160(String udf160);
    public  void setUdf161(String udf161);
    public  void setUdf162(String udf162);
    public  void setUdf163(String udf163);
    public  void setUdf164(String udf164);
    public  void setUdf165(String udf165);
    public  void setUdf166(String udf166);
    public  void setUdf167(String udf167);
    public  void setUdf168(String udf168);
    public  void setUdf169(String udf169);
    public  void setUdf170(String udf170);
    public  void setUdf171(String udf171);
    public  void setUdf172(String udf172);
    public  void setUdf173(String udf173);
    public  void setUdf174(String udf174);
    public  void setUdf175(String udf175);
    public  void setUdf176(String udf176);
    public  void setUdf177(String udf177);
    public  void setUdf178(String udf178);
    public  void setUdf179(String udf179);
    public  void setUdf180(String udf180);
    public  void setUdf181(String udf181);
    public  void setUdf182(String udf182);
    public  void setUdf183(String udf183);
    public  void setUdf184(String udf184);
    public  void setUdf185(String udf185);
    public  void setUdf186(String udf186);
    public  void setUdf187(String udf187);
    public  void setUdf188(String udf188);
    public  void setUdf189(String udf189);
    public  void setUdf190(String udf190);
    public  void setUdf191(String udf191);
    public  void setUdf192(String udf192);
    public  void setUdf193(String udf193);
    public  void setUdf194(String udf194);
    public  void setUdf195(String udf195);
    public  void setUdf196(String udf196);
    public  void setUdf197(String udf197);
    public  void setUdf198(String udf198);
    public  void setUdf199(String udf199);
    public  void setUdf200(String udf200);

    public void setUdf201(String udf201);
	public void setUdf202(String udf202);
	public void setUdf203(String udf203);
	public void setUdf204(String udf204);
	public void setUdf205(String udf205);
	public void setUdf206(String udf206);
	public void setUdf207(String udf207);
	public void setUdf208(String udf208);
	public void setUdf209(String udf209);
	public void setUdf210(String udf210);
	public void setUdf211(String udf211);
	public void setUdf212(String udf212);
	public void setUdf213(String udf213);
	public void setUdf214(String udf214);
	public void setUdf215(String udf215);
    

}
