package com.integrosys.cms.app.bankingArrangementFacExclusion.proxy;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.uiinfra.exception.CommandProcessingException;
import com.integrosys.cms.app.bankingArrangementFacExclusion.bus.BankingArrangementFacExclusionException;
import com.integrosys.cms.app.bankingArrangementFacExclusion.bus.IBankingArrangementFacExclusion;
import com.integrosys.cms.app.bankingArrangementFacExclusion.trx.IBankingArrangementFacExclusionTrxValue;
import com.integrosys.cms.app.transaction.ITrxContext;
import com.integrosys.cms.app.valuationAmountAndRating.bus.ValuationAmountAndRatingException;
import com.integrosys.cms.app.valuationAmountAndRating.trx.IValuationAmountAndRatingTrxValue;

public interface IProxyManager {

	public SearchResult getAllActual() throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue makerCreate(ITrxContext anITrxContext, IBankingArrangementFacExclusion obj)throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue getByTrxID(String aTrxID) throws BankingArrangementFacExclusionException,TransactionException,CommandProcessingException;
	
	public IBankingArrangementFacExclusionTrxValue checkerApprove(ITrxContext anITrxContext, IBankingArrangementFacExclusionTrxValue trx) throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue makerUpdateSaveUpdate(ITrxContext anITrxContext, IBankingArrangementFacExclusionTrxValue trx, IBankingArrangementFacExclusion obj)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue makerSave(ITrxContext anITrxContext, IBankingArrangementFacExclusion obj)throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;

	public IBankingArrangementFacExclusionTrxValue getTrxValue(long id)	throws BankingArrangementFacExclusionException,TransactionException,CommandProcessingException;
	
	public IBankingArrangementFacExclusionTrxValue makerUpdate(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn,
			IBankingArrangementFacExclusion obj)throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue checkerReject(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;

	public IBankingArrangementFacExclusionTrxValue makerEditRejected(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn,IBankingArrangementFacExclusion obj)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;

	public IBankingArrangementFacExclusionTrxValue makerCloseRejected(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;

	public IBankingArrangementFacExclusionTrxValue makerUpdateSaveCreate(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn,IBankingArrangementFacExclusion obj)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue makerCloseDraft(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;
	
	public IBankingArrangementFacExclusionTrxValue makerDelete(ITrxContext ctx, IBankingArrangementFacExclusionTrxValue trxValueIn,IBankingArrangementFacExclusion obj)
			throws BankingArrangementFacExclusionException,TrxParameterException,TransactionException;

}