package com.integrosys.cms.app.systemBankBranch.proxy;

import java.util.ArrayList;
import java.util.List;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.techinfra.ejbsupport.ConcurrentUpdateException;
import com.integrosys.base.uiinfra.exception.CommandProcessingException;
import com.integrosys.cms.app.fileInsertMapper.bus.IFileMapperMaster;
import com.integrosys.cms.app.fileInsertMapper.bus.OBFileMapperID;
import com.integrosys.cms.app.fileInsertMapper.bus.OBFileMapperMaster;
import com.integrosys.cms.app.geography.bus.NoSuchGeographyException;
import com.integrosys.cms.app.systemBankBranch.bus.ISystemBankBranch;
import com.integrosys.cms.app.systemBankBranch.bus.SystemBankBranchException;
import com.integrosys.cms.app.systemBankBranch.trx.ISystemBankBranchTrxValue;
import com.integrosys.cms.app.transaction.ITrxContext;

/**
 * This interface defines the list of attributes that will be available to the
 * generation of a diary item
 * 
 * @author $Author: jtan $<br>
 * @version $Revision: 1.6 $
 * @since $Date: 2004/06/29 10:03:55 $ Tag: $Name: $
 */
public interface ISystemBankBranchProxyManager {

	public SearchResult searchBranch(String login) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public SearchResult getAllActualBranch() throws SystemBankBranchException,TrxParameterException,TransactionException;
	public SearchResult getAllActualBranchForHUB() throws SystemBankBranchException,TrxParameterException,TransactionException;
	
	public SearchResult getSystemBranchList(String branchCode,String branchName,String state,String city);
	public List getAllHUBBranchId() throws SystemBankBranchException,TrxParameterException,TransactionException;
	public List getAllHUBBranchValue() throws SystemBankBranchException,TrxParameterException,TransactionException;
	public SearchResult getAllActual(String searchBy,String searchText) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public List getAllStage(String searchBy, String login) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranch deleteSystemBankBranch(ISystemBankBranch systemBankBranch) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerCloseRejectedSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerCloseDraftSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranch getSystemBankBranchById(long id) throws SystemBankBranchException,TrxParameterException,TransactionException ;
	public ISystemBankBranch updateSystemBankBranch(ISystemBankBranch systemBankBranch) throws SystemBankBranchException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	public ISystemBankBranchTrxValue makerDeleteSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anICCSystemBankBranchTrxValue, ISystemBankBranch anICCSystemBankBranch)throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerUpdateSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anICCSystemBankBranchTrxValue, ISystemBankBranch anICCSystemBankBranch)
	throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerUpdateSaveUpdateSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anICCSystemBankBranchTrxValue, ISystemBankBranch anICCSystemBankBranch)
	throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerUpdateSaveCreateSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anICCSystemBankBranchTrxValue, ISystemBankBranch anICCSystemBankBranch)
	throws SystemBankBranchException,TrxParameterException,TransactionException;
	
	public ISystemBankBranchTrxValue makerEditRejectedSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue, ISystemBankBranch anSystemBankBranch) throws SystemBankBranchException,TrxParameterException,TransactionException;
	
	public ISystemBankBranchTrxValue getSystemBankBranchTrxValue(long aSystemBankBranchId) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue getSystemBankBranchByTrxID(String aTrxID) throws SystemBankBranchException,TransactionException,CommandProcessingException;
	public ISystemBankBranchTrxValue getInsertFileByTrxID(String aTrxID) throws SystemBankBranchException,TransactionException,CommandProcessingException;
	public ISystemBankBranchTrxValue checkerApproveSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue checkerApproveInsertSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue checkerRejectSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue checkerRejectInsertSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerCreateSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranch anICCSystemBankBranch)throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerSaveSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranch anICCSystemBankBranch)throws SystemBankBranchException,TrxParameterException,TransactionException;
	public boolean isUniqueCode(String coloumn ,String branchCode) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerInsertMapperSystemBankBranch(ITrxContext anITrxContext, OBFileMapperID obFileMapperID)throws SystemBankBranchException,TrxParameterException,TransactionException;
	public int insertSystemBankBranch(IFileMapperMaster fileMapperMaster, String userName, ArrayList resultList) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranchTrxValue makerInsertCloseRejectedSystemBankBranch(ITrxContext anITrxContext, ISystemBankBranchTrxValue anISystemBankBranchTrxValue) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public List getFileMasterList(String searchBy) throws SystemBankBranchException,TrxParameterException,TransactionException;
	public ISystemBankBranch insertActualSystemBankBranch(String sysId) throws SystemBankBranchException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	public ISystemBankBranchTrxValue checkerCreateSystemBankBranch(ITrxContext anITrxContext,ISystemBankBranch anICCSystemBankBranch, String refStage)throws SystemBankBranchException,TrxParameterException,TransactionException;
	public boolean isPrevFileUploadPending() throws SystemBankBranchException,TrxParameterException,TransactionException;
	
	public boolean isHubValid(String linkedHub);
	
	public String isCodeExisting(String countryCode,String regionCode,String stateCode,String cityCode) throws SystemBankBranchException,TrxParameterException,TransactionException;
	
	public void deleteTransaction(OBFileMapperMaster obFileMapperMaster) throws NoSuchGeographyException,TrxParameterException,TransactionException;
}
