/*
 * Generated by XDoclet - Do not edit!
 */
package com.integrosys.cms.app.creditriskparam.bus.bankentitybranch;

import com.integrosys.cms.app.common.constant.ICMSConstant;

import java.util.Collection;

/**
 * Data object for OBBankEntityBranchParamList.
 * @generated
 * @wtp generated
 */
public class OBBankEntityBranchParamList
   extends Object
   implements java.io.Serializable, IBankEntityBranchParamList
{
    private String [] deleteItems;

    private Collection bankEntityBranchParams;

    private String lastActionBy;

    private String lastRemarks;

    private String remarks;

    public String[] getDeleteItems() {
        return deleteItems;
    }

    public void setDeleteItems(String[] deleteItems) {
        this.deleteItems = deleteItems;
    }

    public Collection getBankEntityBranchParams() {
        return bankEntityBranchParams;
    }

    public void setBankEntityBranchParams(Collection bankEntityBranchParams) {
        this.bankEntityBranchParams = bankEntityBranchParams;
    }

    public String getLastActionBy() {
        return lastActionBy;
    }

    public void setLastActionBy(String lastActionBy) {
        this.lastActionBy = lastActionBy;
    }

    public String getLastRemarks() {
        return lastRemarks;
    }

    public void setLastRemarks(String lastRemarks) {
        this.lastRemarks = lastRemarks;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}