/*
 * Generated by XDoclet - Do not edit!
 */
package com.integrosys.cms.app.creditriskparam.bus.bankentitybranch;

import com.integrosys.cms.app.common.constant.ICMSConstant;

/**
 * Data object for EBBankEntityBranchParam.
 * @generated 
 * @wtp generated
 */
public class OBBankEntityBranchParam
   extends java.lang.Object
   implements java.io.Serializable, IBankEntityBranchParam, Comparable
{
   private java.lang.Long bankEntityId = new Long(ICMSConstant.LONG_INVALID_VALUE);
   private java.lang.Long groupId = new Long(ICMSConstant.LONG_INVALID_VALUE);
   private java.lang.String entityType;
   private java.lang.String entityTypeDesc;
   private java.lang.String branchCode;
   private java.lang.String branchCodeSrc;
   private java.lang.String status;
   private long versionTime = ICMSConstant.LONG_INVALID_VALUE;
   private long cmsRefId = ICMSConstant.LONG_INVALID_VALUE;

  /* begin value object */

  /* end value object */

   public OBBankEntityBranchParam()
   {
   }

   public OBBankEntityBranchParam( OBBankEntityBranchParam otherData )
   {
      setBankEntityId(otherData.getBankEntityId());
      setGroupId(otherData.getGroupId());
      setEntityType(otherData.getEntityType());
      setBranchCode(otherData.getBranchCode());
      setBranchCodeSrc(otherData.getBranchCodeSrc());
      setStatus(otherData.getStatus());
      setVersionTime(otherData.getVersionTime());
      setCmsRefId(otherData.getCmsRefId());

   }

   public java.lang.Long getPrimaryKey() {
     return  getBankEntityId();
   }

   public java.lang.Long getBankEntityId()
   {
      return this.bankEntityId;
   }
   public void setBankEntityId( java.lang.Long bankEntityId )
   {
      this.bankEntityId = bankEntityId;
   }

   public java.lang.Long getGroupId()
   {
      return this.groupId;
   }
   public void setGroupId( java.lang.Long groupId )
   {
      this.groupId = groupId;
   }

   public java.lang.String getEntityType()
   {
      return this.entityType;
   }
   public void setEntityType( java.lang.String entityType )
   {
      this.entityType = entityType;
   }

   public java.lang.String getBranchCode()
   {
      return this.branchCode;
   }
   public void setBranchCode( java.lang.String branchCode )
   {
      this.branchCode = branchCode;
   }

   public java.lang.String getBranchCodeSrc()
   {
      return this.branchCodeSrc;
   }
   public void setBranchCodeSrc( java.lang.String branchCodeSrc )
   {
      this.branchCodeSrc = branchCodeSrc;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }
   public void setStatus( java.lang.String status )
   {
      this.status = status;
   }

   public long getVersionTime()
   {
      return this.versionTime;
   }
   public void setVersionTime( long versionTime )
   {
      this.versionTime = versionTime;
   }

   public long getCmsRefId()
   {
      return this.cmsRefId;
   }
   public void setCmsRefId( long cmsRefId )
   {
      this.cmsRefId = cmsRefId;
   }

    public String getEntityTypeDesc() {
        return entityTypeDesc;
    }

    public void setEntityTypeDesc(String entityTypeDesc) {
        this.entityTypeDesc = entityTypeDesc;
    }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("bankEntityId=" + getBankEntityId() + " " + "groupId=" + getGroupId() + " " + "entityType=" + getEntityType() + " " + "branchCode=" + getBranchCode() + " " + "branchCodeSrc=" + getBranchCodeSrc() + " " + "status=" + getStatus() + " " + "versionTime=" + getVersionTime() + " " + "cmsRefId=" + getCmsRefId());
      str.append('}');

      return(str.toString());
   }

   public int compareTo(Object ob1) {
		OBBankEntityBranchParam be1 = (OBBankEntityBranchParam) ob1;

		return getEntityTypeDesc().compareTo(be1.getEntityTypeDesc());
	}

}
