/**
 * 
 */
package com.integrosys.cms.batch.sibs.creditapplication;

import java.util.Date;

import com.integrosys.base.techinfra.util.AccessorUtil;
/**
 * @author gp loh
 * date : 26sep08
 * time : 0020hr
 *

Record Type								Alpha	M
AA No.									Alpha	M
Source Limit ID							Numeric	M
Outer Source Limit ID					Numeric	M
Facility Type Code						Alpha	O
Account No.								Alpha	M/O
Account Status							Alpha	O
NPL Status								Alpha	M
Settled									Date	O
Amount Partially Written Off			Numeric	M/O
NPL Date								Date	M/O
Interest in Suspense					Numeric	O
Specific Provision Charge to Account	Numeric	O
Part Payment Received					Numeric	O
Latest Date Doubtful					Date	O
Judgement Date							Date	O
Judgement Sum							Numeric	O
Date Write-Off							Date	O
Amount Written Off						Numeric	O
Months Installments Arrears				Numeric	O
Months Interest Arrears					Numeric	O
Facility Sequence						Numeric	M
Account Type							Alpha	M
Account Sequence						Numeric	M
Location Country						Alpha	M
Location Organisation Code				Alpha	M

 */
public class CreditApplicationNplClosedAcc implements ICreditApplicationNplClosedAcc {

	/* standard variables */
	private long creditAppfeedEntryID;
	private String recordType;
	private String aaNumber;
	private String sourceLimitID;
	private String outerSourceLimitID;
	private String facilityTypeCode;
	private String accountNo;
	private long   facilitySequence;
	private String accountType;
	private long   accountSequence;
	private String locationCountry;
	private String locationOrgCode;

    /** variables pertinent to NPL, Closed account status **/
	private String accountStatus;
	private String nplStatus;
	private Date   dateSettled;
	private double amtPartiallyWrittenOff;
	private Date   dateNPL;
	private double interestInSuspense;
	private double specProvisionChrg2Acc;
	private double partPaymentReceived;
    private Date   dateLatestDoubtful;
    private Date   dateJudgement;
    private double judgementSum;
    private Date   dateWriteOff;
    private double amountWrittenOff;
    private double mthsInstllmtsArrears;
    private double mthsIntrstArrears;
    private String endLineInd;
    //Andy Wong, 17 July 2009: new fields enhancement
    private String facilityStatus;
    private String cancelRejectCode;
    private Date cancelRejectDate;

    /**
	 * Default Constructor
	 */
	public CreditApplicationNplClosedAcc() {
	}

	/**
	 * Construct OB from interface
	 *
	 * @param value is of type ICreditApplication
	 */
	public CreditApplicationNplClosedAcc(ICreditApplication value) {
		this();
		AccessorUtil.copyValue(value, this);
	}

    
	/** 
	 * credit app feed entry id,
	 * generated by CMS_CREDIT_APP_NPL_CLSACC_SEQ,
	 *  in EONCMS database
	 */ 
	public void setCreditAppFeedEntryID(long param) {
		this.creditAppfeedEntryID = param;
	}
	public long getCreditAppFeedEntryID() {
		return creditAppfeedEntryID;
	}

	/*** record type ***/
	public void setRecordType(String recType) {
		this.recordType = recType;
	}
	public String getRecordType() {
		return recordType;
	}

	/** AA Number **/
	public void setAaNumber(String aaNo) {
		this.aaNumber = aaNo;
	}
	public String getAaNumber() {
		return aaNumber;
	}

	/*** source limit ID ***/
	public void setSourceLimitID(String sLimitID) {
		this.sourceLimitID = sLimitID;
	}
	public String getSourceLimitID() {
		return sourceLimitID;
	}

	/*** OUTER source limit ID ***/
	public void setOuterSourceLimitID(String oLimitID) {
		this.outerSourceLimitID = oLimitID;
	}
	public String getOuterSourceLimitID() {
		return outerSourceLimitID;
	}

	/**** facility type code ***/
	public void setFacilityTypeCode(String facTypeCode) {
		this.facilityTypeCode = facTypeCode;
	}
	public String getFacilityTypeCode() {
		return facilityTypeCode;
	}

    /*** Account Number ***/
	public void setAccountNo(String accNo) {
		this.accountNo = accNo;
	}
	public String getAccountNo() {
		return accountNo;
	}


	/* Account Status */
	public void setAccountStatus(String accSts) {
		this.accountStatus = accSts;
	}
	public String getAccountStatus() {
		return accountStatus;
	}

	/* NPL Status */
	public void setNplStatus(String nplSts) {
		this.nplStatus = nplSts;
	}
	public String getNplStatus() {
		return nplStatus;
	}

	/** Date Settled of outstanding amount **/
	public void setDateSettled(Date dtStld) {
		this.dateSettled = dtStld;
	}
	public Date   getDateSettled() {
		return dateSettled;
	}

	/** Amount partially written off **/
	public void setAmtPartiallyWrittenOff(double amtPartWrtOff) {
		this.amtPartiallyWrittenOff = amtPartWrtOff;
	}
	public double getAmtPartiallyWrittenOff() {
		//return new Double( removeLeadingZeros(amtPartiallyWrittenOff, 2, 3));
		return (amtPartiallyWrittenOff/100);
	}

	/** Date of NPL **/
	public void setDateNpl(Date dtNPL) {
		this.dateNPL = dtNPL;
	}
	public Date   getDateNpl() {
		return dateNPL;
	}

	/** Interest in suspense **/
	public void setInterestInSuspense(double intrstInSusp) {
		this.interestInSuspense = intrstInSusp;
	}
	public double getInterestInSuspense() {
		//return new Double( removeLeadingZeros(interestInSuspense, 2, 3));
		return (interestInSuspense/100);
	}

	/** Specific Provision Charge to Account  **/
	public void setSpecProvisionChrgToAccount(double spcProvsnChrg2Acc) {
		this.specProvisionChrg2Acc = spcProvsnChrg2Acc;
	}
	public double getSpecProvisionChrgToAccount() {
		//return new Double( removeLeadingZeros(specProvisionChrg2Acc, 2, 3));
		return (specProvisionChrg2Acc/100);
	}

	/** Partial payment received **/
	public void setPartPaymentReceived(double partPaymtRx) {
		this.partPaymentReceived = partPaymtRx;
	}
	public double getPartPaymentReceived() {
		//return new Double( removeLeadingZeros(partPaymentReceived, 2, 3) );
		return (partPaymentReceived/100);
	}

	/** Date Latest Doubtful **/
    public void setDateLatestDoubtful(Date dtLtstDbtfl) {
    	this.dateLatestDoubtful = dtLtstDbtfl;
    }
    public Date   getDateLatestDoubtful() {
    	return dateLatestDoubtful;
    }

    /** Date of Judgement **/
    public void    setDateJudgement(Date dtJdgmt) {
    	this.dateJudgement = dtJdgmt;
    }
    public Date   getDateJudgement() {
    	return dateJudgement;
    }

    /** Judgement Sum  **/
    public void setJudgementSum(double jdgmtSum) {
    	this.judgementSum = jdgmtSum;
    }
    public double getJudgementSum() {
    	//return new Double( removeLeadingZeros(judgementSum, 2, 3) );
    	return (judgementSum/100);
    }

    /** Date Write Off **/
    public void setDateWriteOff(Date dtWrtOff) {
    	this.dateWriteOff = dtWrtOff;
    }
    public Date   getDateWriteOff() {
    	return dateWriteOff;
    }

    /** Amount Written Off **/
    public void setAmountWrittenOff(double amtWrtnOff) {
    	this.amountWrittenOff = amtWrtnOff;
    }
    public double getAmountWrittenOff() {
    	return (amountWrittenOff/100);
    	//return new Double( removeLeadingZeros(amountWrittenOff, 2, 3 ) );
    	
    }

    /** Months INstallment Arrears ***/
    public void setMonthsInstallmentsArrears(double mthInstlmtArrs) {
    	this.mthsInstllmtsArrears = mthInstlmtArrs;
    }
    public double getMonthsInstallmentsArrears() {
    	return (mthsInstllmtsArrears/100);
    	//return new Double( removeLeadingZeros(mthsInstllmtsArrears, 2, 3 ) );
    }

    /*** MOnths INterest Arrears ***/
    public void setMonthsInterestArrears(double mthsIntrstArrs) {
    	this.mthsIntrstArrears = mthsIntrstArrs;
    }
    public double getMonthsInterestArrears() {
    	return (mthsIntrstArrears/100);
    	//return new Double( removeLeadingZeros(mthsIntrstArrears, 2, 3 ) );
    }

   
	/**** facility sequence ****/
	public void   setFacilitySequence(long seq) {
		this.facilitySequence = seq;
	}
	public long   getFacilitySequence() {
		return facilitySequence;
	}

    /*** Account Type *****/
	public void setAccountType(String accType) {
		this.accountType = accType;
	}
	public String getAccountType() {
		return accountType;
	}

	/**** Account Sequence ****/
	public void   setAccountSequence(long accSeq) {
		this.accountSequence = accSeq;
	}
	public long   getAccountSequence() {
		return accountSequence;
	}

	/***** location country *****/
	public void setLocationCountry(String locCrty) {
		this.locationCountry = locCrty;
	}
	public String getLocationCountry() {
		return locationCountry;
	}

	/**** location organisation code *****/
	public void setLocationOrgCode(String locOrgCode) {
		this.locationOrgCode = locOrgCode;
	}
	public String getLocationOrgCode() {
		return locationOrgCode;
	}

	public void setEndLineIndicator(String end) {
		this.endLineInd = end;
	}
	public String getEndLineIndicator() {
		return endLineInd;
	}

    public String getFacilityStatus() {
        return facilityStatus;
    }

    public void setFacilityStatus(String facilityStatus) {
        this.facilityStatus = facilityStatus;
    }

    public String getCancelRejectCode() {
        return cancelRejectCode;
    }

    public void setCancelRejectCode(String cancelRejectCode) {
        this.cancelRejectCode = cancelRejectCode;
    }

    public Date getCancelRejectDate() {
        return cancelRejectDate;
    }

    public void setCancelRejectDate(Date cancelRejectDate) {
        this.cancelRejectDate = cancelRejectDate;
    }
}
