/**
 * 
 */
package com.integrosys.cms.batch.sibs.creditapplication;

import com.integrosys.base.techinfra.util.AccessorUtil;

import java.util.Date;

/**
 * @author gp loh
 * date 25 sep08
 *
 */
public class CreditApplicationODTL implements ICreditApplicationODTL {

	/** standard variables **/
	private long creditAppfeedEntryID;
	private String recordType;
	private String aaNumber;
	private String sourceLimitID;
	private String outerSourceLimitID;
	private String facilityTypeCode;
	private String accountNo;
	private long   facilitySequence;
	private String accountType;
	private long   accountSequence;
	private String locationCountry;
	private String locationOrgCode;
    private Date   firstDisbursementDate;
    private Date   finalDisbursementDate;

    /** variables pertinent to Overdraft, Term Loan Outstanding **/
	private double  drawingLimit;
    private String  outstdgBalSign;
    private double  outstandingBalance;
    private String endLineInd;

    private double currentBalance;
    private String currentBalanceSign;
    private double finalPaymentAmount;
    private double paymentAmount;
    private double releasedAmount;
    private double lateChargesAmount;
    private double otherChargesAmount;
    private double miscChargesAmount;
    private double billedIntOSAmount;
    private double accruedInterestAmount;
    private double accruedLateChargeAmount;
    private double accruedCommFeeAmount;
    private String primeRateNumber;
    private String primeVarianceSign;
    private double primeVarianceAmount;

    private String finalPaymentAmountSign;
    private String paymentAmountSign;
    private String releasedAmountSign;
    private String lateChargesAmountSign;
    private String otherChargesAmountSign;
    private String miscChargesAmountSign;
    private String billedIntOSAmountSign;
    private String accruedInterestAmountSign;
    private String accruedLateChargeAmountSign;
    private String accruedCommFeeAmountSign;

    /**
	 * Default Constructor
	 */
	public CreditApplicationODTL() {
	}

	/**
	 * Construct OB from interface
	 *
	 * @param value is of type ICreditApplication
	 */
	public CreditApplicationODTL(ICreditApplication value) {
		this();
		AccessorUtil.copyValue(value, this);
	}


	/** 
	 * credit app feed entry id,
	 * generated by CMS_CREDIT_APP_OD_TL_SEQ,
	 *  in EONCMS database
	 */ 
	public void setCreditAppFeedEntryID(long param) {
		this.creditAppfeedEntryID = param;
	}
	public long getCreditAppFeedEntryID() {
		return creditAppfeedEntryID;
	}

	/*** record type ***/
	public void setRecordType(String recType) {
		this.recordType = recType;
	}
	public String getRecordType() {
		return recordType;
	}

    /** AA Number **/
	public void setAaNumber(String aaNo) {
		this.aaNumber = aaNo;
	}
	public String getAaNumber() {
		return aaNumber;
	}

    /*** source limit ID ***/
	public void setSourceLimitID(String sLimitID) {
		this.sourceLimitID = sLimitID;
	}
	public String getSourceLimitID() {
		return sourceLimitID;
	}

	/*** OUTER source limit ID ***/
	public void setOuterSourceLimitID(String oLimitID) {
		this.outerSourceLimitID = oLimitID;
	}
	public String getOuterSourceLimitID() {
		return outerSourceLimitID;
	}

	/**** facility type code ***/
	public void setFacilityTypeCode(String facTypeCode) {
		this.facilityTypeCode = facTypeCode;
	}
	public String getFacilityTypeCode() {
		return facilityTypeCode;
	}

    /*** Account Number ***/
	public void setAccountNo(String accNo) {
		this.accountNo = accNo;
	}
	public String getAccountNo() {
		return accountNo;
	}

	/**** facility sequence ****/
	public void   setFacilitySequence(long seq) {
		this.facilitySequence = seq;
	}
	public long   getFacilitySequence() {
		return facilitySequence;
	}

    /*** Account Type *****/
	public void setAccountType(String accType) {
		this.accountType = accType;
	}
	public String getAccountType() {
		return accountType;
	}

	/**** Account Sequence ****/
	public void   setAccountSequence(long accSeq) {
		this.accountSequence = accSeq;
	}
	public long   getAccountSequence() {
		return accountSequence;
	}

	/***** location country *****/
	public void setLocationCountry(String locCrty) {
		this.locationCountry = locCrty;
	}
	public String getLocationCountry() {
		return locationCountry;
	}

	/**** location organisation code *****/
	public void setLocationOrgCode(String locOrgCode) {
		this.locationOrgCode = locOrgCode;
	}
	public String getLocationOrgCode() {
		return locationOrgCode;
	}

    /**** First Disbursement Date *****/
    public Date getFirstDisbursementDate() {
        return firstDisbursementDate;
    }

    public void setFirstDisbursementDate(Date firstDisbursementDate) {
        this.firstDisbursementDate = firstDisbursementDate;
    }

    /**** Final Disbursement Date *****/
    public Date getFinalDisbursementDate() {
        return finalDisbursementDate;
    }

    public void setFinalDisbursementDate(Date finalDisbursementDate) {
        this.finalDisbursementDate = finalDisbursementDate;
    }

    /********************************************************************************
	 * setter , getter methods pertinent to OD , TL Oustanding Balance only.
	 * 
	 * *****************************************************************************/

	public void setDrawingLimit(double dLimit) {
		this.drawingLimit = dLimit;
	}
	public double getDrawingLimit() {
		//return new Double(removeLeadingZeros(drawingLimit, 2, 3) );
		return (drawingLimit/100);
	}

	public void setOutstdgBalSign(String ostdgBalSign) {
		this.outstdgBalSign = ostdgBalSign;
	}
	public String getOutstdgBalSign() {
		return outstdgBalSign;
	}

	public void setOutstandingBalance(double outstdBalance) {
		this.outstandingBalance = outstdBalance;
	}
	public double getOutstandingBalance() {
		//return new Double( removeLeadingZeros(outstandingBalance, 2, 3) );
		return (outstandingBalance/100);
	}

	public void setEndLineIndicator(String end) {
		this.endLineInd = end;
	}
	public String getEndLineIndicator() {
		return endLineInd;
	}


    public double getPrimeVarianceAmount() {
        return (primeVarianceAmount/1000000000);
    }

    public void setPrimeVarianceAmount(double primeVarianceAmount) {
        this.primeVarianceAmount = primeVarianceAmount;
    }

    public String getPrimeVarianceSign() {
        return primeVarianceSign;
    }

    public void setPrimeVarianceSign(String primeVarianceSign) {
        this.primeVarianceSign = primeVarianceSign;
    }

    public String getPrimeRateNumber() {
        return primeRateNumber;
    }

    public void setPrimeRateNumber(String primeRateNumber) {
        this.primeRateNumber = primeRateNumber;
    }

    public double getAccruedCommFeeAmount() {
        return (accruedCommFeeAmount/100000);
    }

    public void setAccruedCommFeeAmount(double accruedCommFeeAmount) {
        this.accruedCommFeeAmount = accruedCommFeeAmount;
    }

    public double getAccruedLateChargeAmount() {
        return (accruedLateChargeAmount/100000);
    }

    public void setAccruedLateChargeAmount(double accruedLateChargeAmount) {
        this.accruedLateChargeAmount = accruedLateChargeAmount;
    }

    public double getAccruedInterestAmount() {
        return (accruedInterestAmount/100000);
    }

    public void setAccruedInterestAmount(double accruedInterestAmount) {
        this.accruedInterestAmount = accruedInterestAmount;
    }

    public double getBilledIntOSAmount() {
        return (billedIntOSAmount/100);
    }

    public void setBilledIntOSAmount(double billedIntOSAmount) {
        this.billedIntOSAmount = billedIntOSAmount;
    }

    public double getMiscChargesAmount() {
        return (miscChargesAmount/100);
    }

    public void setMiscChargesAmount(double miscChargesAmount) {
        this.miscChargesAmount = miscChargesAmount;
    }

    public double getOtherChargesAmount() {
        return (otherChargesAmount/100);
    }

    public void setOtherChargesAmount(double otherChargesAmount) {
        this.otherChargesAmount = otherChargesAmount;
    }

    public double getLateChargesAmount() {
        return (lateChargesAmount/100);
    }

    public void setLateChargesAmount(double lateChargesAmount) {
        this.lateChargesAmount = lateChargesAmount;
    }

    public double getReleasedAmount() {
        return (releasedAmount/100);
    }

    public void setReleasedAmount(double releasedAmount) {
        this.releasedAmount = releasedAmount;
    }

    public double getPaymentAmount() {
        return (paymentAmount/100);
    }

    public void setPaymentAmount(double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public double getFinalPaymentAmount() {
        return (finalPaymentAmount/100);
    }

    public void setFinalPaymentAmount(double finalPaymentAmount) {
        this.finalPaymentAmount = finalPaymentAmount;
    }

    public String getCurrentBalanceSign() {
        return currentBalanceSign;
    }

    public void setCurrentBalanceSign(String currentBalanceSign) {
        this.currentBalanceSign = currentBalanceSign;
    }

    public double getCurrentBalance() {
        return (currentBalance/100);
    }

    public void setCurrentBalance(double currentBalance) {
        this.currentBalance = currentBalance;
    }

    public String getFinalPaymentAmountSign() {
        return finalPaymentAmountSign;
    }

    public void setFinalPaymentAmountSign(String finalPaymentAmountSign) {
        this.finalPaymentAmountSign = finalPaymentAmountSign;
    }

    public String getPaymentAmountSign() {
        return paymentAmountSign;
    }

    public void setPaymentAmountSign(String paymentAmountSign) {
        this.paymentAmountSign = paymentAmountSign;
    }

    public String getReleasedAmountSign() {
        return releasedAmountSign;
    }

    public void setReleasedAmountSign(String releasedAmountSign) {
        this.releasedAmountSign = releasedAmountSign;
    }

    public String getLateChargesAmountSign() {
        return lateChargesAmountSign;
    }

    public void setLateChargesAmountSign(String lateChargesAmountSign) {
        this.lateChargesAmountSign = lateChargesAmountSign;
    }

    public String getOtherChargesAmountSign() {
        return otherChargesAmountSign;
    }

    public void setOtherChargesAmountSign(String otherChargesAmountSign) {
        this.otherChargesAmountSign = otherChargesAmountSign;
    }

    public String getMiscChargesAmountSign() {
        return miscChargesAmountSign;
    }

    public void setMiscChargesAmountSign(String miscChargesAmountSign) {
        this.miscChargesAmountSign = miscChargesAmountSign;
    }

    public String getBilledIntOSAmountSign() {
        return billedIntOSAmountSign;
    }

    public void setBilledIntOSAmountSign(String billedIntOSAmountSign) {
        this.billedIntOSAmountSign = billedIntOSAmountSign;
    }

    public String getAccruedInterestAmountSign() {
        return accruedInterestAmountSign;
    }

    public void setAccruedInterestAmountSign(String accruedInterestAmountSign) {
        this.accruedInterestAmountSign = accruedInterestAmountSign;
    }

    public String getAccruedLateChargeAmountSign() {
        return accruedLateChargeAmountSign;
    }

    public void setAccruedLateChargeAmountSign(String accruedLateChargeAmountSign) {
        this.accruedLateChargeAmountSign = accruedLateChargeAmountSign;
    }

    public String getAccruedCommFeeAmountSign() {
        return accruedCommFeeAmountSign;
    }

    public void setAccruedCommFeeAmountSign(String accruedCommFeeAmountSign) {
        this.accruedCommFeeAmountSign = accruedCommFeeAmountSign;
    }
}
