/**
 * 
 */
package com.integrosys.cms.batch.sibs.creditapplication;

/**
 * @author gp loh
 * @date   25sep08
 * @time   2150
 */
public interface ICreditApplication {

	/** credit app feed entry id,
	 * 
	 * generated by CMS respective 
	 * credit app SEQ in db
	 * 
	 *  **/
	public void setCreditAppFeedEntryID(long param);
	public long getCreditAppFeedEntryID();

    /*** record type ***/
	public void setRecordType(String recType);
	public String getRecordType();

    /** AA Number **/
	public void setAaNumber(String aaNo);
	public String getAaNumber();

    /*** source limit ID ***/
	public void setSourceLimitID(String sLimitID);
	public String getSourceLimitID();

	/*** OUTER source limit ID ***/
	public void setOuterSourceLimitID(String oLimitID);
	public String getOuterSourceLimitID();

	/**** facility type code ***/
	public void setFacilityTypeCode(String FacTypeCode);
	public String getFacilityTypeCode();

    /*** Account Number ***/
	public void setAccountNo(String accNo);
	public String getAccountNo();

	/**** facility sequence ****/
	public void   setFacilitySequence(long seq);
	public long   getFacilitySequence();

    /*** Account Type *****/
	public void setAccountType(String accType);
	public String getAccountType();

	/**** Account Sequence ****/
	public void   setAccountSequence(long accSeq);
	public long   getAccountSequence();

	/***** location country *****/
	public void setLocationCountry(String locCrty);
	public String getLocationCountry();

	/**** location organisatioin code *****/
	public void setLocationOrgCode(String locOrgCode);
	public String getLocationOrgCode();

}
