package com.integrosys.cms.app.valuationAmountAndRating.bus;

import com.integrosys.base.businfra.search.SearchResult;
import com.integrosys.base.businfra.transaction.TransactionException;
import com.integrosys.base.businfra.transaction.TrxParameterException;
import com.integrosys.base.techinfra.ejbsupport.ConcurrentUpdateException;
import com.integrosys.cms.app.fccBranch.bus.FCCBranchException;
import com.integrosys.cms.app.fccBranch.bus.IFCCBranch;

public interface IValuationAmountAndRatingBusManager {

	SearchResult getAllValuationAmountAndRating()throws ValuationAmountAndRatingException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IValuationAmountAndRating createValuationAmountAndRating(IValuationAmountAndRating valuationAmountAndRating)throws ValuationAmountAndRatingException;
	IValuationAmountAndRating getValuationAmountAndRatingById(long id) throws ValuationAmountAndRatingException,TrxParameterException,TransactionException;
	IValuationAmountAndRating updateValuationAmountAndRating(IValuationAmountAndRating item) throws ValuationAmountAndRatingException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	public boolean isProductCodeUnique(String productCode);
	IValuationAmountAndRating updateToWorkingCopy(IValuationAmountAndRating workingCopy, IValuationAmountAndRating imageCopy) throws ValuationAmountAndRatingException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	SearchResult getAllFilteredValuationAmountAndRating(String code,String name)throws ValuationAmountAndRatingException,TrxParameterException,TransactionException,ConcurrentUpdateException;
	IValuationAmountAndRating deleteToWorkingCopy(IValuationAmountAndRating workingCopy, IValuationAmountAndRating imageCopy) throws ValuationAmountAndRatingException,TrxParameterException,TransactionException,ConcurrentUpdateException;
}
