
package com.hdfcbank.wsdl.isd.panval;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.hdfcbank.xsd.isd.panval.ObjectFactory;
import com.hdfcbank.xsd.isd.panval.PANValServiceRequestType;
import com.hdfcbank.xsd.isd.panval.PANValServiceResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PANValServicePortType", targetNamespace = "panval.isd.wsdl.hdfcbank.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PANValServicePortType {


    /**
     * Takes upto 5 PAN Numbers and other details as request and gives individual PAN details as response
     * 
     * @param body
     * @return
     *     returns com.hdfcbank.xsd.isd.panval.PANValServiceResponseType
     */
    @WebMethod(operationName = "ExecutePANValService")
    @WebResult(name = "PANValServiceResponse", targetNamespace = "panval.isd.xsd.hdfcbank.com", partName = "body")
    public PANValServiceResponseType executePANValService(
        @WebParam(name = "PANValServiceRequest", targetNamespace = "panval.isd.xsd.hdfcbank.com", partName = "body")
        PANValServiceRequestType body);

}
