
package com.hdfcbank.wsdl.isd.panval;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.integrosys.base.techinfra.propertyfile.PropertyManager;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchPANValServiceQSService", targetNamespace = "panval.isd.wsdl.hdfcbank.com", wsdlLocation = "file:/C:/Users/santosh.sonmankar/AppData/Local/Temp/tempdir13764460842129315327.tmp/PANVerification_V1_1.wsdl")
public class SearchPANValServiceQSService
    extends Service
{

    private final static URL SEARCHPANVALSERVICEQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHPANVALSERVICEQSSERVICE_EXCEPTION;
    private final static QName SEARCHPANVALSERVICEQSSERVICE_QNAME = new QName("panval.isd.wsdl.hdfcbank.com", "SearchPANValServiceQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PropertyManager.getValue("PAN_NSDL_WS_URL") +"?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHPANVALSERVICEQSSERVICE_WSDL_LOCATION = url;
        SEARCHPANVALSERVICEQSSERVICE_EXCEPTION = e;
    }

    public SearchPANValServiceQSService() {
        super(__getWsdlLocation(), SEARCHPANVALSERVICEQSSERVICE_QNAME);
    }

    /*public SearchPANValServiceQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHPANVALSERVICEQSSERVICE_QNAME, features);
    }*/

    public SearchPANValServiceQSService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHPANVALSERVICEQSSERVICE_QNAME);
    }

    /*public SearchPANValServiceQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHPANVALSERVICEQSSERVICE_QNAME, features);
    }*/

    public SearchPANValServiceQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /*public SearchPANValServiceQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns PANValServicePortType
     */
    @WebEndpoint(name = "SearchPANValServiceQSPort")
    public PANValServicePortType getSearchPANValServiceQSPort() {
        return super.getPort(new QName("panval.isd.wsdl.hdfcbank.com", "SearchPANValServiceQSPort"), PANValServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PANValServicePortType
     */
    @WebEndpoint(name = "SearchPANValServiceQSPort")
    public PANValServicePortType getSearchPANValServiceQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("panval.isd.wsdl.hdfcbank.com", "SearchPANValServiceQSPort"), PANValServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHPANVALSERVICEQSSERVICE_EXCEPTION!= null) {
            throw SEARCHPANVALSERVICEQSSERVICE_EXCEPTION;
        }
        return SEARCHPANVALSERVICEQSSERVICE_WSDL_LOCATION;
    }

}
